-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity window_macc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    window_0_0_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_0_1_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_0_2_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_1_0_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_1_1_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_1_2_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_2_0_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_2_1_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    window_2_2_val_V_r : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read211 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read312 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read413 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read514 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read615 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read716 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read817 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of window_macc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

    signal mul_ln1118_fu_3186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_reg_3276 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_3285 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_fu_203_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_reg_3291 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_s_reg_3296 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_1_reg_3301 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_16_fu_3196_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_16_reg_3307 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_262_reg_3316 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_16_fu_239_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_16_reg_3322 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_0_1_reg_3327 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_0_1_reg_3332 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_17_fu_3206_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_17_reg_3338 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_271_reg_3347 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_17_fu_275_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_17_reg_3353 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_0_2_reg_3358 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_0_2_reg_3363 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_18_fu_3216_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_18_reg_3369 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_280_reg_3378 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_18_fu_311_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_18_reg_3384 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_1_reg_3389 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_1_reg_3394 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_19_fu_3226_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_19_reg_3400 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_289_reg_3409 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_19_fu_347_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_19_reg_3415 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_1_1_reg_3420 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_1_1_reg_3425 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_20_fu_3236_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_20_reg_3431 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_298_reg_3440 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_20_fu_383_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_20_reg_3446 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_1_2_reg_3451 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_1_2_reg_3456 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_21_fu_3246_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_21_reg_3462 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_307_reg_3471 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_21_fu_419_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_21_reg_3477 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_2_reg_3482 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_2_reg_3487 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_22_fu_3256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_22_reg_3493 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_316_reg_3502 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_22_fu_455_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_22_reg_3508 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_2_1_reg_3513 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_2_1_reg_3518 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_23_fu_3266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1118_23_reg_3524 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_325_reg_3533 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln718_23_fu_491_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln718_23_reg_3539 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_42_2_2_reg_3544 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_2_2_reg_3549 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln415_fu_563_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_reg_3555 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_reg_3561 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_16_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_16_reg_3566 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_reg_3571 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_48_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_48_reg_3576 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_reg_3581 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_16_fu_756_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_16_reg_3586 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_16_fu_840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_16_reg_3592 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_18_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_18_reg_3597 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_49_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_49_reg_3602 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_50_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_50_reg_3607 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_50_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_50_reg_3612 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_17_fu_949_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_17_reg_3617 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_17_fu_1033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_17_reg_3623 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_20_fu_1051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_20_reg_3628 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_52_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_52_reg_3633 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_53_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_53_reg_3638 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_54_fu_1085_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_54_reg_3643 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_18_fu_1142_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_18_reg_3648 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_18_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_18_reg_3654 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_22_fu_1244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_22_reg_3659 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_55_fu_1255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_55_reg_3664 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_56_fu_1273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_56_reg_3669 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_58_fu_1278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_58_reg_3674 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_19_fu_1335_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_19_reg_3679 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_19_fu_1419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_19_reg_3685 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_24_fu_1437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_24_reg_3690 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_58_fu_1448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_58_reg_3695 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_59_fu_1466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_59_reg_3700 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_62_fu_1471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_62_reg_3705 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_20_fu_1528_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_20_reg_3710 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_20_fu_1612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_20_reg_3716 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_26_fu_1630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_26_reg_3721 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_61_fu_1641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_61_reg_3726 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_62_fu_1659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_62_reg_3731 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_66_fu_1664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_66_reg_3736 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_21_fu_1721_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_21_reg_3741 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_21_fu_1805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_21_reg_3747 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_28_fu_1823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_28_reg_3752 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_64_fu_1834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_64_reg_3757 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_65_fu_1852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_65_reg_3762 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_70_fu_1857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_70_reg_3767 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_22_fu_1914_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_22_reg_3772 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_22_fu_1998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_22_reg_3778 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_30_fu_2016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_30_reg_3783 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_67_fu_2027_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_67_reg_3788 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_68_fu_2045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_68_reg_3793 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_74_fu_2050_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_74_reg_3798 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln415_23_fu_2107_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln415_23_reg_3803 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln781_23_fu_2191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_23_reg_3809 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_32_fu_2209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_32_reg_3814 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_70_fu_2220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_70_reg_3819 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_71_fu_2238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_71_reg_3824 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_78_fu_2243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_78_reg_3829 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_278_reg_3834 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_47_fu_2448_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_47_reg_3841 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_279_reg_3847 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_85_fu_2483_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_85_reg_3854 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_87_fu_2512_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_87_reg_3860 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_89_fu_2541_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_89_reg_3866 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_89_reg_3866_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_91_fu_2570_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_91_reg_3872 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_91_reg_3872_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_93_fu_2599_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_93_reg_3878 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_93_reg_3878_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_93_reg_3878_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_95_fu_2628_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_95_reg_3884 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_95_reg_3884_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_95_reg_3884_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_296_reg_3890 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_49_fu_2791_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_49_reg_3897 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_297_reg_3903 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_314_reg_3910 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_51_fu_2959_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_51_reg_3917 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_315_reg_3923 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_332_reg_3930 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_53_fu_3127_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_53_reg_3937 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_333_reg_3943 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln718_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_256_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_258_fu_546_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_559_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln4_fu_512_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_259_fu_569_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_257_fu_533_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_261_fu_620_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_fu_612_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_260_fu_589_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_fu_639_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_16_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_263_fu_714_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_265_fu_739_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_16_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_16_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_16_fu_752_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_s_fu_705_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_266_fu_762_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_264_fu_726_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_47_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_16_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_3_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_1_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_268_fu_813_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_2_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_16_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_1_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_1_fu_805_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_267_fu_782_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_17_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_16_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_1_fu_832_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_32_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_32_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_1_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_17_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_272_fu_907_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_274_fu_932_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_17_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_17_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_17_fu_945_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_15_fu_898_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_275_fu_955_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_273_fu_919_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_48_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_17_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_5_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_2_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_277_fu_1006_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_4_fu_983_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_17_fu_1013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_2_fu_1019_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_2_fu_998_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_276_fu_975_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_19_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_17_fu_1045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_2_fu_1025_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_33_fu_1068_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_34_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_2_fu_1056_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_18_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_281_fu_1100_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_283_fu_1125_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_18_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_18_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_18_fu_1138_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_16_fu_1091_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_284_fu_1148_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_282_fu_1112_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_49_fu_1156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_18_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_7_fu_1181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_3_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_286_fu_1199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_6_fu_1176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_18_fu_1206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_3_fu_1212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_3_fu_1191_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_285_fu_1168_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_21_fu_1232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_18_fu_1238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_3_fu_1218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_34_fu_1261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_36_fu_1267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_3_fu_1249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_19_fu_1300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_290_fu_1293_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_292_fu_1318_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_19_fu_1312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_19_fu_1325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_19_fu_1331_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_17_fu_1284_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_293_fu_1341_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_291_fu_1305_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_50_fu_1349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_19_fu_1355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_9_fu_1374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_4_fu_1379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_295_fu_1392_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_8_fu_1369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_19_fu_1399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_4_fu_1405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_4_fu_1384_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_294_fu_1361_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_23_fu_1425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_19_fu_1431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_4_fu_1411_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_35_fu_1454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_38_fu_1460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_4_fu_1442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_20_fu_1493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_299_fu_1486_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_301_fu_1511_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_20_fu_1505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_20_fu_1518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_20_fu_1524_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_18_fu_1477_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_302_fu_1534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_300_fu_1498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_51_fu_1542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_20_fu_1548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_11_fu_1567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_5_fu_1572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_304_fu_1585_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_10_fu_1562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_20_fu_1592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_5_fu_1598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_5_fu_1577_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_303_fu_1554_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_25_fu_1618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_20_fu_1624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_5_fu_1604_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_36_fu_1647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_40_fu_1653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_5_fu_1635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_21_fu_1686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_308_fu_1679_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_310_fu_1704_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_21_fu_1698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_21_fu_1711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_21_fu_1717_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_19_fu_1670_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_311_fu_1727_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_309_fu_1691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_52_fu_1735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_21_fu_1741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_13_fu_1760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_6_fu_1765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_313_fu_1778_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_12_fu_1755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_21_fu_1785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_6_fu_1791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_6_fu_1770_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_312_fu_1747_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_27_fu_1811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_21_fu_1817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_6_fu_1797_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_37_fu_1840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_42_fu_1846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_6_fu_1828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_22_fu_1879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_317_fu_1872_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_319_fu_1897_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_22_fu_1891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_22_fu_1904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_22_fu_1910_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_20_fu_1863_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_320_fu_1920_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_318_fu_1884_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_53_fu_1928_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_22_fu_1934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_15_fu_1953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_7_fu_1958_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_322_fu_1971_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_14_fu_1948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_22_fu_1978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_7_fu_1984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_7_fu_1963_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_321_fu_1940_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_29_fu_2004_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_22_fu_2010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_7_fu_1990_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_38_fu_2033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_44_fu_2039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_7_fu_2021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln718_23_fu_2072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_326_fu_2065_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_328_fu_2090_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln412_23_fu_2084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln415_23_fu_2097_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_23_fu_2103_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_21_fu_2056_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_329_fu_2113_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_327_fu_2077_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_54_fu_2121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln416_23_fu_2127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_17_fu_2146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln768_8_fu_2151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_331_fu_2164_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_16_fu_2141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln779_23_fu_2171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln779_8_fu_2177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln777_8_fu_2156_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_330_fu_2133_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_31_fu_2197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_23_fu_2203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln416_8_fu_2183_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln786_39_fu_2226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_46_fu_2232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln785_8_fu_2214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_48_fu_2249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_49_fu_2253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_2258_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_fu_2264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_51_fu_2278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_52_fu_2282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_64_fu_2287_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_32_fu_2293_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_80_fu_2270_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_81_fu_2299_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_fu_2307_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_96_fu_2311_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_fu_2315_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln703_fu_2329_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_270_fu_2335_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_269_fu_2321_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_33_fu_2343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_48_fu_2361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_2355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_51_fu_2349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_53_fu_2367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_65_fu_2373_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_33_fu_2381_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_55_fu_2397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_56_fu_2401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_66_fu_2406_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_34_fu_2412_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_82_fu_2389_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_83_fu_2418_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_97_fu_2426_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_98_fu_2430_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_64_fu_2434_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln340_59_fu_2462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_60_fu_2466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_68_fu_2471_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_36_fu_2477_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_63_fu_2491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_64_fu_2495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_70_fu_2500_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_38_fu_2506_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_67_fu_2520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_68_fu_2524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_72_fu_2529_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_40_fu_2535_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_71_fu_2549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_72_fu_2553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_74_fu_2558_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_42_fu_2564_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_75_fu_2578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_76_fu_2582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_76_fu_2587_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_44_fu_2593_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_79_fu_2607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_80_fu_2611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_78_fu_2616_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_46_fu_2622_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln786_35_fu_2636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_50_fu_2650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_49_fu_2646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_54_fu_2641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_57_fu_2655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_67_fu_2660_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_35_fu_2667_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_84_fu_2674_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_99_fu_2682_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_100_fu_2686_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_65_fu_2689_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln703_48_fu_2703_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_288_fu_2708_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_287_fu_2695_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_37_fu_2716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_52_fu_2734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_51_fu_2728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_57_fu_2722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_61_fu_2740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_69_fu_2746_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_37_fu_2754_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_86_fu_2762_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_101_fu_2770_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_102_fu_2774_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_66_fu_2777_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal xor_ln786_39_fu_2804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_54_fu_2818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_53_fu_2814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_60_fu_2809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_65_fu_2823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_71_fu_2828_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_39_fu_2835_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_88_fu_2842_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_103_fu_2850_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_104_fu_2854_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_67_fu_2857_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln703_50_fu_2871_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_306_fu_2876_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_305_fu_2863_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_41_fu_2884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_56_fu_2902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_55_fu_2896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_63_fu_2890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_69_fu_2908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_73_fu_2914_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_41_fu_2922_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_90_fu_2930_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_105_fu_2938_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_106_fu_2942_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_68_fu_2945_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal xor_ln786_43_fu_2972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_58_fu_2986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_57_fu_2982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_66_fu_2977_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_73_fu_2991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_75_fu_2996_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_43_fu_3003_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_92_fu_3010_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_107_fu_3018_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_108_fu_3022_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_69_fu_3025_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln703_52_fu_3039_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_324_fu_3044_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_323_fu_3031_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_45_fu_3052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_60_fu_3070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_59_fu_3064_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_69_fu_3058_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_77_fu_3076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_77_fu_3082_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_45_fu_3090_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_94_fu_3098_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln703_109_fu_3106_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln703_110_fu_3110_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1192_70_fu_3113_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal xor_ln786_47_fu_3140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_62_fu_3154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_61_fu_3150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_72_fu_3145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_81_fu_3159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_79_fu_3164_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_47_fu_3171_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_96_fu_3178_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal window_0_0_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_0_1_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_0_2_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_1_0_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_1_1_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_1_2_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_2_0_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_2_1_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal window_2_2_val_V_r_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read9_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read110_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read211_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read312_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read413_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read514_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read615_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read716_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read817_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component yolo_conv_top_mul_mul_16s_16s_32_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    yolo_conv_top_mul_mul_16s_16s_32_1_0_U10 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read9_int_reg,
        din1 => window_0_0_val_V_r_int_reg,
        dout => mul_ln1118_fu_3186_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U11 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read110_int_reg,
        din1 => window_0_1_val_V_r_int_reg,
        dout => mul_ln1118_16_fu_3196_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U12 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read211_int_reg,
        din1 => window_0_2_val_V_r_int_reg,
        dout => mul_ln1118_17_fu_3206_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U13 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read312_int_reg,
        din1 => window_1_0_val_V_r_int_reg,
        dout => mul_ln1118_18_fu_3216_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U14 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read413_int_reg,
        din1 => window_1_1_val_V_r_int_reg,
        dout => mul_ln1118_19_fu_3226_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U15 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read514_int_reg,
        din1 => window_1_2_val_V_r_int_reg,
        dout => mul_ln1118_20_fu_3236_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U16 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read615_int_reg,
        din1 => window_2_0_val_V_r_int_reg,
        dout => mul_ln1118_21_fu_3246_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U17 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read716_int_reg,
        din1 => window_2_1_val_V_r_int_reg,
        dout => mul_ln1118_22_fu_3256_p2);

    yolo_conv_top_mul_mul_16s_16s_32_1_0_U18 : component yolo_conv_top_mul_mul_16s_16s_32_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => p_read817_int_reg,
        din1 => window_2_2_val_V_r_int_reg,
        dout => mul_ln1118_23_fu_3266_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln415_16_reg_3586 <= add_ln415_16_fu_756_p2;
                add_ln415_17_reg_3617 <= add_ln415_17_fu_949_p2;
                add_ln415_18_reg_3648 <= add_ln415_18_fu_1142_p2;
                add_ln415_19_reg_3679 <= add_ln415_19_fu_1335_p2;
                add_ln415_20_reg_3710 <= add_ln415_20_fu_1528_p2;
                add_ln415_21_reg_3741 <= add_ln415_21_fu_1721_p2;
                add_ln415_22_reg_3772 <= add_ln415_22_fu_1914_p2;
                add_ln415_23_reg_3803 <= add_ln415_23_fu_2107_p2;
                add_ln415_reg_3555 <= add_ln415_fu_563_p2;
                add_ln703_47_reg_3841 <= add_ln703_47_fu_2448_p2;
                add_ln703_49_reg_3897 <= add_ln703_49_fu_2791_p2;
                add_ln703_51_reg_3917 <= add_ln703_51_fu_2959_p2;
                add_ln703_53_reg_3937 <= add_ln703_53_fu_3127_p2;
                and_ln781_16_reg_3592 <= and_ln781_16_fu_840_p2;
                and_ln781_17_reg_3623 <= and_ln781_17_fu_1033_p2;
                and_ln781_18_reg_3654 <= and_ln781_18_fu_1226_p2;
                and_ln781_19_reg_3685 <= and_ln781_19_fu_1419_p2;
                and_ln781_20_reg_3716 <= and_ln781_20_fu_1612_p2;
                and_ln781_21_reg_3747 <= and_ln781_21_fu_1805_p2;
                and_ln781_22_reg_3778 <= and_ln781_22_fu_1998_p2;
                and_ln781_23_reg_3809 <= and_ln781_23_fu_2191_p2;
                and_ln781_reg_3561 <= and_ln781_fu_647_p2;
                and_ln786_48_reg_3576 <= and_ln786_48_fu_694_p2;
                and_ln786_49_reg_3602 <= and_ln786_49_fu_869_p2;
                and_ln786_50_reg_3607 <= and_ln786_50_fu_887_p2;
                and_ln786_52_reg_3633 <= and_ln786_52_fu_1062_p2;
                and_ln786_53_reg_3638 <= and_ln786_53_fu_1080_p2;
                and_ln786_55_reg_3664 <= and_ln786_55_fu_1255_p2;
                and_ln786_56_reg_3669 <= and_ln786_56_fu_1273_p2;
                and_ln786_58_reg_3695 <= and_ln786_58_fu_1448_p2;
                and_ln786_59_reg_3700 <= and_ln786_59_fu_1466_p2;
                and_ln786_61_reg_3726 <= and_ln786_61_fu_1641_p2;
                and_ln786_62_reg_3731 <= and_ln786_62_fu_1659_p2;
                and_ln786_64_reg_3757 <= and_ln786_64_fu_1834_p2;
                and_ln786_65_reg_3762 <= and_ln786_65_fu_1852_p2;
                and_ln786_67_reg_3788 <= and_ln786_67_fu_2027_p2;
                and_ln786_68_reg_3793 <= and_ln786_68_fu_2045_p2;
                and_ln786_70_reg_3819 <= and_ln786_70_fu_2220_p2;
                and_ln786_71_reg_3824 <= and_ln786_71_fu_2238_p2;
                and_ln786_reg_3571 <= and_ln786_fu_676_p2;
                mul_ln1118_16_reg_3307 <= mul_ln1118_16_fu_3196_p2;
                mul_ln1118_17_reg_3338 <= mul_ln1118_17_fu_3206_p2;
                mul_ln1118_18_reg_3369 <= mul_ln1118_18_fu_3216_p2;
                mul_ln1118_19_reg_3400 <= mul_ln1118_19_fu_3226_p2;
                mul_ln1118_20_reg_3431 <= mul_ln1118_20_fu_3236_p2;
                mul_ln1118_21_reg_3462 <= mul_ln1118_21_fu_3246_p2;
                mul_ln1118_22_reg_3493 <= mul_ln1118_22_fu_3256_p2;
                mul_ln1118_23_reg_3524 <= mul_ln1118_23_fu_3266_p2;
                mul_ln1118_reg_3276 <= mul_ln1118_fu_3186_p2;
                or_ln340_50_reg_3612 <= or_ln340_50_fu_892_p2;
                or_ln340_54_reg_3643 <= or_ln340_54_fu_1085_p2;
                or_ln340_58_reg_3674 <= or_ln340_58_fu_1278_p2;
                or_ln340_62_reg_3705 <= or_ln340_62_fu_1471_p2;
                or_ln340_66_reg_3736 <= or_ln340_66_fu_1664_p2;
                or_ln340_70_reg_3767 <= or_ln340_70_fu_1857_p2;
                or_ln340_74_reg_3798 <= or_ln340_74_fu_2050_p2;
                or_ln340_78_reg_3829 <= or_ln340_78_fu_2243_p2;
                or_ln340_reg_3581 <= or_ln340_fu_699_p2;
                p_Result_1_reg_3301 <= mul_ln1118_fu_3186_p2(31 downto 24);
                p_Result_42_0_1_reg_3327 <= mul_ln1118_16_fu_3196_p2(31 downto 25);
                p_Result_42_0_2_reg_3358 <= mul_ln1118_17_fu_3206_p2(31 downto 25);
                p_Result_42_1_1_reg_3420 <= mul_ln1118_19_fu_3226_p2(31 downto 25);
                p_Result_42_1_2_reg_3451 <= mul_ln1118_20_fu_3236_p2(31 downto 25);
                p_Result_42_1_reg_3389 <= mul_ln1118_18_fu_3216_p2(31 downto 25);
                p_Result_42_2_1_reg_3513 <= mul_ln1118_22_fu_3256_p2(31 downto 25);
                p_Result_42_2_2_reg_3544 <= mul_ln1118_23_fu_3266_p2(31 downto 25);
                p_Result_42_2_reg_3482 <= mul_ln1118_21_fu_3246_p2(31 downto 25);
                p_Result_43_0_1_reg_3332 <= mul_ln1118_16_fu_3196_p2(31 downto 24);
                p_Result_43_0_2_reg_3363 <= mul_ln1118_17_fu_3206_p2(31 downto 24);
                p_Result_43_1_1_reg_3425 <= mul_ln1118_19_fu_3226_p2(31 downto 24);
                p_Result_43_1_2_reg_3456 <= mul_ln1118_20_fu_3236_p2(31 downto 24);
                p_Result_43_1_reg_3394 <= mul_ln1118_18_fu_3216_p2(31 downto 24);
                p_Result_43_2_1_reg_3518 <= mul_ln1118_22_fu_3256_p2(31 downto 24);
                p_Result_43_2_2_reg_3549 <= mul_ln1118_23_fu_3266_p2(31 downto 24);
                p_Result_43_2_reg_3487 <= mul_ln1118_21_fu_3246_p2(31 downto 24);
                p_Result_s_reg_3296 <= mul_ln1118_fu_3186_p2(31 downto 25);
                select_ln340_85_reg_3854 <= select_ln340_85_fu_2483_p3;
                select_ln340_87_reg_3860 <= select_ln340_87_fu_2512_p3;
                select_ln340_89_reg_3866 <= select_ln340_89_fu_2541_p3;
                select_ln340_89_reg_3866_pp0_iter3_reg <= select_ln340_89_reg_3866;
                select_ln340_91_reg_3872 <= select_ln340_91_fu_2570_p3;
                select_ln340_91_reg_3872_pp0_iter3_reg <= select_ln340_91_reg_3872;
                select_ln340_93_reg_3878 <= select_ln340_93_fu_2599_p3;
                select_ln340_93_reg_3878_pp0_iter3_reg <= select_ln340_93_reg_3878;
                select_ln340_93_reg_3878_pp0_iter4_reg <= select_ln340_93_reg_3878_pp0_iter3_reg;
                select_ln340_95_reg_3884 <= select_ln340_95_fu_2628_p3;
                select_ln340_95_reg_3884_pp0_iter3_reg <= select_ln340_95_reg_3884;
                select_ln340_95_reg_3884_pp0_iter4_reg <= select_ln340_95_reg_3884_pp0_iter3_reg;
                tmp_262_reg_3316 <= mul_ln1118_16_fu_3196_p2(31 downto 31);
                tmp_271_reg_3347 <= mul_ln1118_17_fu_3206_p2(31 downto 31);
                tmp_278_reg_3834 <= add_ln1192_64_fu_2434_p2(16 downto 16);
                tmp_279_reg_3847 <= add_ln703_47_fu_2448_p2(15 downto 15);
                tmp_280_reg_3378 <= mul_ln1118_18_fu_3216_p2(31 downto 31);
                tmp_289_reg_3409 <= mul_ln1118_19_fu_3226_p2(31 downto 31);
                tmp_296_reg_3890 <= add_ln1192_66_fu_2777_p2(16 downto 16);
                tmp_297_reg_3903 <= add_ln703_49_fu_2791_p2(15 downto 15);
                tmp_298_reg_3440 <= mul_ln1118_20_fu_3236_p2(31 downto 31);
                tmp_307_reg_3471 <= mul_ln1118_21_fu_3246_p2(31 downto 31);
                tmp_314_reg_3910 <= add_ln1192_68_fu_2945_p2(16 downto 16);
                tmp_315_reg_3923 <= add_ln703_51_fu_2959_p2(15 downto 15);
                tmp_316_reg_3502 <= mul_ln1118_22_fu_3256_p2(31 downto 31);
                tmp_325_reg_3533 <= mul_ln1118_23_fu_3266_p2(31 downto 31);
                tmp_332_reg_3930 <= add_ln1192_70_fu_3113_p2(16 downto 16);
                tmp_333_reg_3943 <= add_ln703_53_fu_3127_p2(15 downto 15);
                tmp_reg_3285 <= mul_ln1118_fu_3186_p2(31 downto 31);
                trunc_ln718_16_reg_3322 <= trunc_ln718_16_fu_239_p1;
                trunc_ln718_17_reg_3353 <= trunc_ln718_17_fu_275_p1;
                trunc_ln718_18_reg_3384 <= trunc_ln718_18_fu_311_p1;
                trunc_ln718_19_reg_3415 <= trunc_ln718_19_fu_347_p1;
                trunc_ln718_20_reg_3446 <= trunc_ln718_20_fu_383_p1;
                trunc_ln718_21_reg_3477 <= trunc_ln718_21_fu_419_p1;
                trunc_ln718_22_reg_3508 <= trunc_ln718_22_fu_455_p1;
                trunc_ln718_23_reg_3539 <= trunc_ln718_23_fu_491_p1;
                trunc_ln718_reg_3291 <= trunc_ln718_fu_203_p1;
                xor_ln785_16_reg_3566 <= xor_ln785_16_fu_665_p2;
                xor_ln785_18_reg_3597 <= xor_ln785_18_fu_858_p2;
                xor_ln785_20_reg_3628 <= xor_ln785_20_fu_1051_p2;
                xor_ln785_22_reg_3659 <= xor_ln785_22_fu_1244_p2;
                xor_ln785_24_reg_3690 <= xor_ln785_24_fu_1437_p2;
                xor_ln785_26_reg_3721 <= xor_ln785_26_fu_1630_p2;
                xor_ln785_28_reg_3752 <= xor_ln785_28_fu_1823_p2;
                xor_ln785_30_reg_3783 <= xor_ln785_30_fu_2016_p2;
                xor_ln785_32_reg_3814 <= xor_ln785_32_fu_2209_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln340_96_fu_3178_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read110_int_reg <= p_read110;
                p_read211_int_reg <= p_read211;
                p_read312_int_reg <= p_read312;
                p_read413_int_reg <= p_read413;
                p_read514_int_reg <= p_read514;
                p_read615_int_reg <= p_read615;
                p_read716_int_reg <= p_read716;
                p_read817_int_reg <= p_read817;
                p_read9_int_reg <= p_read9;
                window_0_0_val_V_r_int_reg <= window_0_0_val_V_r;
                window_0_1_val_V_r_int_reg <= window_0_1_val_V_r;
                window_0_2_val_V_r_int_reg <= window_0_2_val_V_r;
                window_1_0_val_V_r_int_reg <= window_1_0_val_V_r;
                window_1_1_val_V_r_int_reg <= window_1_1_val_V_r;
                window_1_2_val_V_r_int_reg <= window_1_2_val_V_r;
                window_2_0_val_V_r_int_reg <= window_2_0_val_V_r;
                window_2_1_val_V_r_int_reg <= window_2_1_val_V_r;
                window_2_2_val_V_r_int_reg <= window_2_2_val_V_r;
            end if;
        end if;
    end process;
    add_ln1192_64_fu_2434_p2 <= std_logic_vector(signed(sext_ln703_97_fu_2426_p1) + signed(sext_ln703_98_fu_2430_p1));
    add_ln1192_65_fu_2689_p2 <= std_logic_vector(signed(sext_ln703_99_fu_2682_p1) + signed(sext_ln703_100_fu_2686_p1));
    add_ln1192_66_fu_2777_p2 <= std_logic_vector(signed(sext_ln703_101_fu_2770_p1) + signed(sext_ln703_102_fu_2774_p1));
    add_ln1192_67_fu_2857_p2 <= std_logic_vector(signed(sext_ln703_103_fu_2850_p1) + signed(sext_ln703_104_fu_2854_p1));
    add_ln1192_68_fu_2945_p2 <= std_logic_vector(signed(sext_ln703_105_fu_2938_p1) + signed(sext_ln703_106_fu_2942_p1));
    add_ln1192_69_fu_3025_p2 <= std_logic_vector(signed(sext_ln703_107_fu_3018_p1) + signed(sext_ln703_108_fu_3022_p1));
    add_ln1192_70_fu_3113_p2 <= std_logic_vector(signed(sext_ln703_109_fu_3106_p1) + signed(sext_ln703_110_fu_3110_p1));
    add_ln1192_fu_2315_p2 <= std_logic_vector(signed(sext_ln703_fu_2307_p1) + signed(sext_ln703_96_fu_2311_p1));
    add_ln415_16_fu_756_p2 <= std_logic_vector(unsigned(zext_ln415_16_fu_752_p1) + unsigned(trunc_ln708_s_fu_705_p4));
    add_ln415_17_fu_949_p2 <= std_logic_vector(unsigned(zext_ln415_17_fu_945_p1) + unsigned(trunc_ln708_15_fu_898_p4));
    add_ln415_18_fu_1142_p2 <= std_logic_vector(unsigned(zext_ln415_18_fu_1138_p1) + unsigned(trunc_ln708_16_fu_1091_p4));
    add_ln415_19_fu_1335_p2 <= std_logic_vector(unsigned(zext_ln415_19_fu_1331_p1) + unsigned(trunc_ln708_17_fu_1284_p4));
    add_ln415_20_fu_1528_p2 <= std_logic_vector(unsigned(zext_ln415_20_fu_1524_p1) + unsigned(trunc_ln708_18_fu_1477_p4));
    add_ln415_21_fu_1721_p2 <= std_logic_vector(unsigned(zext_ln415_21_fu_1717_p1) + unsigned(trunc_ln708_19_fu_1670_p4));
    add_ln415_22_fu_1914_p2 <= std_logic_vector(unsigned(zext_ln415_22_fu_1910_p1) + unsigned(trunc_ln708_20_fu_1863_p4));
    add_ln415_23_fu_2107_p2 <= std_logic_vector(unsigned(zext_ln415_23_fu_2103_p1) + unsigned(trunc_ln708_21_fu_2056_p4));
    add_ln415_fu_563_p2 <= std_logic_vector(unsigned(zext_ln415_fu_559_p1) + unsigned(trunc_ln4_fu_512_p4));
    add_ln703_47_fu_2448_p2 <= std_logic_vector(signed(select_ln340_83_fu_2418_p3) + signed(select_ln340_82_fu_2389_p3));
    add_ln703_48_fu_2703_p2 <= std_logic_vector(signed(select_ln340_85_reg_3854) + signed(select_ln340_84_fu_2674_p3));
    add_ln703_49_fu_2791_p2 <= std_logic_vector(signed(select_ln340_87_reg_3860) + signed(select_ln340_86_fu_2762_p3));
    add_ln703_50_fu_2871_p2 <= std_logic_vector(signed(select_ln340_89_reg_3866_pp0_iter3_reg) + signed(select_ln340_88_fu_2842_p3));
    add_ln703_51_fu_2959_p2 <= std_logic_vector(signed(select_ln340_91_reg_3872_pp0_iter3_reg) + signed(select_ln340_90_fu_2930_p3));
    add_ln703_52_fu_3039_p2 <= std_logic_vector(signed(select_ln340_93_reg_3878_pp0_iter4_reg) + signed(select_ln340_92_fu_3010_p3));
    add_ln703_53_fu_3127_p2 <= std_logic_vector(signed(select_ln340_95_reg_3884_pp0_iter4_reg) + signed(select_ln340_94_fu_3098_p3));
    add_ln703_fu_2329_p2 <= std_logic_vector(signed(select_ln340_81_fu_2299_p3) + signed(select_ln340_80_fu_2270_p3));
    and_ln415_16_fu_746_p2 <= (tmp_265_fu_739_p3 and or_ln412_16_fu_733_p2);
    and_ln415_17_fu_939_p2 <= (tmp_274_fu_932_p3 and or_ln412_17_fu_926_p2);
    and_ln415_18_fu_1132_p2 <= (tmp_283_fu_1125_p3 and or_ln412_18_fu_1119_p2);
    and_ln415_19_fu_1325_p2 <= (tmp_292_fu_1318_p3 and or_ln412_19_fu_1312_p2);
    and_ln415_20_fu_1518_p2 <= (tmp_301_fu_1511_p3 and or_ln412_20_fu_1505_p2);
    and_ln415_21_fu_1711_p2 <= (tmp_310_fu_1704_p3 and or_ln412_21_fu_1698_p2);
    and_ln415_22_fu_1904_p2 <= (tmp_319_fu_1897_p3 and or_ln412_22_fu_1891_p2);
    and_ln415_23_fu_2097_p2 <= (tmp_328_fu_2090_p3 and or_ln412_23_fu_2084_p2);
    and_ln415_fu_553_p2 <= (tmp_258_fu_546_p3 and or_ln412_fu_540_p2);
    and_ln416_16_fu_776_p2 <= (xor_ln416_47_fu_770_p2 and tmp_264_fu_726_p3);
    and_ln416_17_fu_969_p2 <= (xor_ln416_48_fu_963_p2 and tmp_273_fu_919_p3);
    and_ln416_18_fu_1162_p2 <= (xor_ln416_49_fu_1156_p2 and tmp_282_fu_1112_p3);
    and_ln416_19_fu_1355_p2 <= (xor_ln416_50_fu_1349_p2 and tmp_291_fu_1305_p3);
    and_ln416_20_fu_1548_p2 <= (xor_ln416_51_fu_1542_p2 and tmp_300_fu_1498_p3);
    and_ln416_21_fu_1741_p2 <= (xor_ln416_52_fu_1735_p2 and tmp_309_fu_1691_p3);
    and_ln416_22_fu_1934_p2 <= (xor_ln416_53_fu_1928_p2 and tmp_318_fu_1884_p3);
    and_ln416_23_fu_2127_p2 <= (xor_ln416_54_fu_2121_p2 and tmp_327_fu_2077_p3);
    and_ln416_fu_583_p2 <= (xor_ln416_fu_577_p2 and tmp_257_fu_533_p3);
    and_ln779_1_fu_826_p2 <= (xor_ln779_16_fu_820_p2 and icmp_ln879_2_fu_790_p2);
    and_ln779_2_fu_1019_p2 <= (xor_ln779_17_fu_1013_p2 and icmp_ln879_4_fu_983_p2);
    and_ln779_3_fu_1212_p2 <= (xor_ln779_18_fu_1206_p2 and icmp_ln879_6_fu_1176_p2);
    and_ln779_4_fu_1405_p2 <= (xor_ln779_19_fu_1399_p2 and icmp_ln879_8_fu_1369_p2);
    and_ln779_5_fu_1598_p2 <= (xor_ln779_20_fu_1592_p2 and icmp_ln879_10_fu_1562_p2);
    and_ln779_6_fu_1791_p2 <= (xor_ln779_21_fu_1785_p2 and icmp_ln879_12_fu_1755_p2);
    and_ln779_7_fu_1984_p2 <= (xor_ln779_22_fu_1978_p2 and icmp_ln879_14_fu_1948_p2);
    and_ln779_8_fu_2177_p2 <= (xor_ln779_23_fu_2171_p2 and icmp_ln879_16_fu_2141_p2);
    and_ln779_fu_633_p2 <= (xor_ln779_fu_627_p2 and icmp_ln879_fu_597_p2);
    and_ln781_16_fu_840_p2 <= (icmp_ln879_3_fu_795_p2 and and_ln416_16_fu_776_p2);
    and_ln781_17_fu_1033_p2 <= (icmp_ln879_5_fu_988_p2 and and_ln416_17_fu_969_p2);
    and_ln781_18_fu_1226_p2 <= (icmp_ln879_7_fu_1181_p2 and and_ln416_18_fu_1162_p2);
    and_ln781_19_fu_1419_p2 <= (icmp_ln879_9_fu_1374_p2 and and_ln416_19_fu_1355_p2);
    and_ln781_20_fu_1612_p2 <= (icmp_ln879_11_fu_1567_p2 and and_ln416_20_fu_1548_p2);
    and_ln781_21_fu_1805_p2 <= (icmp_ln879_13_fu_1760_p2 and and_ln416_21_fu_1741_p2);
    and_ln781_22_fu_1998_p2 <= (icmp_ln879_15_fu_1953_p2 and and_ln416_22_fu_1934_p2);
    and_ln781_23_fu_2191_p2 <= (icmp_ln879_17_fu_2146_p2 and and_ln416_23_fu_2127_p2);
    and_ln781_fu_647_p2 <= (icmp_ln879_1_fu_602_p2 and and_ln416_fu_583_p2);
    and_ln785_1_fu_863_p2 <= (xor_ln785_18_fu_858_p2 and or_ln785_16_fu_852_p2);
    and_ln785_2_fu_1056_p2 <= (xor_ln785_20_fu_1051_p2 and or_ln785_17_fu_1045_p2);
    and_ln785_3_fu_1249_p2 <= (xor_ln785_22_fu_1244_p2 and or_ln785_18_fu_1238_p2);
    and_ln785_4_fu_1442_p2 <= (xor_ln785_24_fu_1437_p2 and or_ln785_19_fu_1431_p2);
    and_ln785_5_fu_1635_p2 <= (xor_ln785_26_fu_1630_p2 and or_ln785_20_fu_1624_p2);
    and_ln785_6_fu_1828_p2 <= (xor_ln785_28_fu_1823_p2 and or_ln785_21_fu_1817_p2);
    and_ln785_7_fu_2021_p2 <= (xor_ln785_30_fu_2016_p2 and or_ln785_22_fu_2010_p2);
    and_ln785_8_fu_2214_p2 <= (xor_ln785_32_fu_2209_p2 and or_ln785_23_fu_2203_p2);
    and_ln785_fu_670_p2 <= (xor_ln785_16_fu_665_p2 and or_ln785_fu_659_p2);
    and_ln786_48_fu_694_p2 <= (xor_ln786_fu_688_p2 and tmp_reg_3285);
    and_ln786_49_fu_869_p2 <= (tmp_267_fu_782_p3 and select_ln416_1_fu_832_p3);
    and_ln786_50_fu_887_p2 <= (xor_ln786_32_fu_881_p2 and tmp_262_reg_3316);
    and_ln786_51_fu_2349_p2 <= (xor_ln786_33_fu_2343_p2 and tmp_269_fu_2321_p3);
    and_ln786_52_fu_1062_p2 <= (tmp_276_fu_975_p3 and select_ln416_2_fu_1025_p3);
    and_ln786_53_fu_1080_p2 <= (xor_ln786_34_fu_1074_p2 and tmp_271_reg_3347);
    and_ln786_54_fu_2641_p2 <= (xor_ln786_35_fu_2636_p2 and tmp_278_reg_3834);
    and_ln786_55_fu_1255_p2 <= (tmp_285_fu_1168_p3 and select_ln416_3_fu_1218_p3);
    and_ln786_56_fu_1273_p2 <= (xor_ln786_36_fu_1267_p2 and tmp_280_reg_3378);
    and_ln786_57_fu_2722_p2 <= (xor_ln786_37_fu_2716_p2 and tmp_287_fu_2695_p3);
    and_ln786_58_fu_1448_p2 <= (tmp_294_fu_1361_p3 and select_ln416_4_fu_1411_p3);
    and_ln786_59_fu_1466_p2 <= (xor_ln786_38_fu_1460_p2 and tmp_289_reg_3409);
    and_ln786_60_fu_2809_p2 <= (xor_ln786_39_fu_2804_p2 and tmp_296_reg_3890);
    and_ln786_61_fu_1641_p2 <= (tmp_303_fu_1554_p3 and select_ln416_5_fu_1604_p3);
    and_ln786_62_fu_1659_p2 <= (xor_ln786_40_fu_1653_p2 and tmp_298_reg_3440);
    and_ln786_63_fu_2890_p2 <= (xor_ln786_41_fu_2884_p2 and tmp_305_fu_2863_p3);
    and_ln786_64_fu_1834_p2 <= (tmp_312_fu_1747_p3 and select_ln416_6_fu_1797_p3);
    and_ln786_65_fu_1852_p2 <= (xor_ln786_42_fu_1846_p2 and tmp_307_reg_3471);
    and_ln786_66_fu_2977_p2 <= (xor_ln786_43_fu_2972_p2 and tmp_314_reg_3910);
    and_ln786_67_fu_2027_p2 <= (tmp_321_fu_1940_p3 and select_ln416_7_fu_1990_p3);
    and_ln786_68_fu_2045_p2 <= (xor_ln786_44_fu_2039_p2 and tmp_316_reg_3502);
    and_ln786_69_fu_3058_p2 <= (xor_ln786_45_fu_3052_p2 and tmp_323_fu_3031_p3);
    and_ln786_70_fu_2220_p2 <= (tmp_330_fu_2133_p3 and select_ln416_8_fu_2183_p3);
    and_ln786_71_fu_2238_p2 <= (xor_ln786_46_fu_2232_p2 and tmp_325_reg_3533);
    and_ln786_72_fu_3145_p2 <= (xor_ln786_47_fu_3140_p2 and tmp_332_reg_3930);
    and_ln786_fu_676_p2 <= (tmp_260_fu_589_p3 and select_ln416_fu_639_p3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln340_96_fu_3178_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln340_96_fu_3178_p3;
        end if; 
    end process;

    icmp_ln718_16_fu_721_p2 <= "0" when (trunc_ln718_16_reg_3322 = ap_const_lv7_0) else "1";
    icmp_ln718_17_fu_914_p2 <= "0" when (trunc_ln718_17_reg_3353 = ap_const_lv7_0) else "1";
    icmp_ln718_18_fu_1107_p2 <= "0" when (trunc_ln718_18_reg_3384 = ap_const_lv7_0) else "1";
    icmp_ln718_19_fu_1300_p2 <= "0" when (trunc_ln718_19_reg_3415 = ap_const_lv7_0) else "1";
    icmp_ln718_20_fu_1493_p2 <= "0" when (trunc_ln718_20_reg_3446 = ap_const_lv7_0) else "1";
    icmp_ln718_21_fu_1686_p2 <= "0" when (trunc_ln718_21_reg_3477 = ap_const_lv7_0) else "1";
    icmp_ln718_22_fu_1879_p2 <= "0" when (trunc_ln718_22_reg_3508 = ap_const_lv7_0) else "1";
    icmp_ln718_23_fu_2072_p2 <= "0" when (trunc_ln718_23_reg_3539 = ap_const_lv7_0) else "1";
    icmp_ln718_fu_528_p2 <= "0" when (trunc_ln718_reg_3291 = ap_const_lv7_0) else "1";
    icmp_ln768_1_fu_800_p2 <= "1" when (p_Result_43_0_1_reg_3332 = ap_const_lv8_0) else "0";
    icmp_ln768_2_fu_993_p2 <= "1" when (p_Result_43_0_2_reg_3363 = ap_const_lv8_0) else "0";
    icmp_ln768_3_fu_1186_p2 <= "1" when (p_Result_43_1_reg_3394 = ap_const_lv8_0) else "0";
    icmp_ln768_4_fu_1379_p2 <= "1" when (p_Result_43_1_1_reg_3425 = ap_const_lv8_0) else "0";
    icmp_ln768_5_fu_1572_p2 <= "1" when (p_Result_43_1_2_reg_3456 = ap_const_lv8_0) else "0";
    icmp_ln768_6_fu_1765_p2 <= "1" when (p_Result_43_2_reg_3487 = ap_const_lv8_0) else "0";
    icmp_ln768_7_fu_1958_p2 <= "1" when (p_Result_43_2_1_reg_3518 = ap_const_lv8_0) else "0";
    icmp_ln768_8_fu_2151_p2 <= "1" when (p_Result_43_2_2_reg_3549 = ap_const_lv8_0) else "0";
    icmp_ln768_fu_607_p2 <= "1" when (p_Result_1_reg_3301 = ap_const_lv8_0) else "0";
    icmp_ln879_10_fu_1562_p2 <= "1" when (p_Result_42_1_2_reg_3451 = ap_const_lv7_7F) else "0";
    icmp_ln879_11_fu_1567_p2 <= "1" when (p_Result_43_1_2_reg_3456 = ap_const_lv8_FF) else "0";
    icmp_ln879_12_fu_1755_p2 <= "1" when (p_Result_42_2_reg_3482 = ap_const_lv7_7F) else "0";
    icmp_ln879_13_fu_1760_p2 <= "1" when (p_Result_43_2_reg_3487 = ap_const_lv8_FF) else "0";
    icmp_ln879_14_fu_1948_p2 <= "1" when (p_Result_42_2_1_reg_3513 = ap_const_lv7_7F) else "0";
    icmp_ln879_15_fu_1953_p2 <= "1" when (p_Result_43_2_1_reg_3518 = ap_const_lv8_FF) else "0";
    icmp_ln879_16_fu_2141_p2 <= "1" when (p_Result_42_2_2_reg_3544 = ap_const_lv7_7F) else "0";
    icmp_ln879_17_fu_2146_p2 <= "1" when (p_Result_43_2_2_reg_3549 = ap_const_lv8_FF) else "0";
    icmp_ln879_1_fu_602_p2 <= "1" when (p_Result_1_reg_3301 = ap_const_lv8_FF) else "0";
    icmp_ln879_2_fu_790_p2 <= "1" when (p_Result_42_0_1_reg_3327 = ap_const_lv7_7F) else "0";
    icmp_ln879_3_fu_795_p2 <= "1" when (p_Result_43_0_1_reg_3332 = ap_const_lv8_FF) else "0";
    icmp_ln879_4_fu_983_p2 <= "1" when (p_Result_42_0_2_reg_3358 = ap_const_lv7_7F) else "0";
    icmp_ln879_5_fu_988_p2 <= "1" when (p_Result_43_0_2_reg_3363 = ap_const_lv8_FF) else "0";
    icmp_ln879_6_fu_1176_p2 <= "1" when (p_Result_42_1_reg_3389 = ap_const_lv7_7F) else "0";
    icmp_ln879_7_fu_1181_p2 <= "1" when (p_Result_43_1_reg_3394 = ap_const_lv8_FF) else "0";
    icmp_ln879_8_fu_1369_p2 <= "1" when (p_Result_42_1_1_reg_3420 = ap_const_lv7_7F) else "0";
    icmp_ln879_9_fu_1374_p2 <= "1" when (p_Result_43_1_1_reg_3425 = ap_const_lv8_FF) else "0";
    icmp_ln879_fu_597_p2 <= "1" when (p_Result_s_reg_3296 = ap_const_lv7_7F) else "0";
    or_ln340_48_fu_2249_p2 <= (xor_ln785_16_reg_3566 or and_ln786_reg_3571);
    or_ln340_49_fu_2253_p2 <= (or_ln340_48_fu_2249_p2 or and_ln781_reg_3561);
    or_ln340_50_fu_892_p2 <= (and_ln786_50_fu_887_p2 or and_ln785_1_fu_863_p2);
    or_ln340_51_fu_2278_p2 <= (xor_ln785_18_reg_3597 or and_ln786_49_reg_3602);
    or_ln340_52_fu_2282_p2 <= (or_ln340_51_fu_2278_p2 or and_ln781_16_reg_3592);
    or_ln340_53_fu_2367_p2 <= (xor_ln340_48_fu_2361_p2 or tmp_270_fu_2335_p3);
    or_ln340_54_fu_1085_p2 <= (and_ln786_53_fu_1080_p2 or and_ln785_2_fu_1056_p2);
    or_ln340_55_fu_2397_p2 <= (xor_ln785_20_reg_3628 or and_ln786_52_reg_3633);
    or_ln340_56_fu_2401_p2 <= (or_ln340_55_fu_2397_p2 or and_ln781_17_reg_3623);
    or_ln340_57_fu_2655_p2 <= (xor_ln340_50_fu_2650_p2 or tmp_279_reg_3847);
    or_ln340_58_fu_1278_p2 <= (and_ln786_56_fu_1273_p2 or and_ln785_3_fu_1249_p2);
    or_ln340_59_fu_2462_p2 <= (xor_ln785_22_reg_3659 or and_ln786_55_reg_3664);
    or_ln340_60_fu_2466_p2 <= (or_ln340_59_fu_2462_p2 or and_ln781_18_reg_3654);
    or_ln340_61_fu_2740_p2 <= (xor_ln340_52_fu_2734_p2 or tmp_288_fu_2708_p3);
    or_ln340_62_fu_1471_p2 <= (and_ln786_59_fu_1466_p2 or and_ln785_4_fu_1442_p2);
    or_ln340_63_fu_2491_p2 <= (xor_ln785_24_reg_3690 or and_ln786_58_reg_3695);
    or_ln340_64_fu_2495_p2 <= (or_ln340_63_fu_2491_p2 or and_ln781_19_reg_3685);
    or_ln340_65_fu_2823_p2 <= (xor_ln340_54_fu_2818_p2 or tmp_297_reg_3903);
    or_ln340_66_fu_1664_p2 <= (and_ln786_62_fu_1659_p2 or and_ln785_5_fu_1635_p2);
    or_ln340_67_fu_2520_p2 <= (xor_ln785_26_reg_3721 or and_ln786_61_reg_3726);
    or_ln340_68_fu_2524_p2 <= (or_ln340_67_fu_2520_p2 or and_ln781_20_reg_3716);
    or_ln340_69_fu_2908_p2 <= (xor_ln340_56_fu_2902_p2 or tmp_306_fu_2876_p3);
    or_ln340_70_fu_1857_p2 <= (and_ln786_65_fu_1852_p2 or and_ln785_6_fu_1828_p2);
    or_ln340_71_fu_2549_p2 <= (xor_ln785_28_reg_3752 or and_ln786_64_reg_3757);
    or_ln340_72_fu_2553_p2 <= (or_ln340_71_fu_2549_p2 or and_ln781_21_reg_3747);
    or_ln340_73_fu_2991_p2 <= (xor_ln340_58_fu_2986_p2 or tmp_315_reg_3923);
    or_ln340_74_fu_2050_p2 <= (and_ln786_68_fu_2045_p2 or and_ln785_7_fu_2021_p2);
    or_ln340_75_fu_2578_p2 <= (xor_ln785_30_reg_3783 or and_ln786_67_reg_3788);
    or_ln340_76_fu_2582_p2 <= (or_ln340_75_fu_2578_p2 or and_ln781_22_reg_3778);
    or_ln340_77_fu_3076_p2 <= (xor_ln340_60_fu_3070_p2 or tmp_324_fu_3044_p3);
    or_ln340_78_fu_2243_p2 <= (and_ln786_71_fu_2238_p2 or and_ln785_8_fu_2214_p2);
    or_ln340_79_fu_2607_p2 <= (xor_ln785_32_reg_3814 or and_ln786_70_reg_3819);
    or_ln340_80_fu_2611_p2 <= (or_ln340_79_fu_2607_p2 or and_ln781_23_reg_3809);
    or_ln340_81_fu_3159_p2 <= (xor_ln340_62_fu_3154_p2 or tmp_333_reg_3943);
    or_ln340_fu_699_p2 <= (and_ln786_48_fu_694_p2 or and_ln785_fu_670_p2);
    or_ln412_16_fu_733_p2 <= (tmp_263_fu_714_p3 or icmp_ln718_16_fu_721_p2);
    or_ln412_17_fu_926_p2 <= (tmp_272_fu_907_p3 or icmp_ln718_17_fu_914_p2);
    or_ln412_18_fu_1119_p2 <= (tmp_281_fu_1100_p3 or icmp_ln718_18_fu_1107_p2);
    or_ln412_19_fu_1312_p2 <= (tmp_290_fu_1293_p3 or icmp_ln718_19_fu_1300_p2);
    or_ln412_20_fu_1505_p2 <= (tmp_299_fu_1486_p3 or icmp_ln718_20_fu_1493_p2);
    or_ln412_21_fu_1698_p2 <= (tmp_308_fu_1679_p3 or icmp_ln718_21_fu_1686_p2);
    or_ln412_22_fu_1891_p2 <= (tmp_317_fu_1872_p3 or icmp_ln718_22_fu_1879_p2);
    or_ln412_23_fu_2084_p2 <= (tmp_326_fu_2065_p3 or icmp_ln718_23_fu_2072_p2);
    or_ln412_fu_540_p2 <= (tmp_256_fu_521_p3 or icmp_ln718_fu_528_p2);
    or_ln785_16_fu_852_p2 <= (xor_ln785_17_fu_846_p2 or tmp_267_fu_782_p3);
    or_ln785_17_fu_1045_p2 <= (xor_ln785_19_fu_1039_p2 or tmp_276_fu_975_p3);
    or_ln785_18_fu_1238_p2 <= (xor_ln785_21_fu_1232_p2 or tmp_285_fu_1168_p3);
    or_ln785_19_fu_1431_p2 <= (xor_ln785_23_fu_1425_p2 or tmp_294_fu_1361_p3);
    or_ln785_20_fu_1624_p2 <= (xor_ln785_25_fu_1618_p2 or tmp_303_fu_1554_p3);
    or_ln785_21_fu_1817_p2 <= (xor_ln785_27_fu_1811_p2 or tmp_312_fu_1747_p3);
    or_ln785_22_fu_2010_p2 <= (xor_ln785_29_fu_2004_p2 or tmp_321_fu_1940_p3);
    or_ln785_23_fu_2203_p2 <= (xor_ln785_31_fu_2197_p2 or tmp_330_fu_2133_p3);
    or_ln785_fu_659_p2 <= (xor_ln785_fu_653_p2 or tmp_260_fu_589_p3);
    or_ln786_32_fu_875_p2 <= (and_ln786_49_fu_869_p2 or and_ln781_16_fu_840_p2);
    or_ln786_33_fu_1068_p2 <= (and_ln786_52_fu_1062_p2 or and_ln781_17_fu_1033_p2);
    or_ln786_34_fu_1261_p2 <= (and_ln786_55_fu_1255_p2 or and_ln781_18_fu_1226_p2);
    or_ln786_35_fu_1454_p2 <= (and_ln786_58_fu_1448_p2 or and_ln781_19_fu_1419_p2);
    or_ln786_36_fu_1647_p2 <= (and_ln786_61_fu_1641_p2 or and_ln781_20_fu_1612_p2);
    or_ln786_37_fu_1840_p2 <= (and_ln786_64_fu_1834_p2 or and_ln781_21_fu_1805_p2);
    or_ln786_38_fu_2033_p2 <= (and_ln786_67_fu_2027_p2 or and_ln781_22_fu_1998_p2);
    or_ln786_39_fu_2226_p2 <= (and_ln786_70_fu_2220_p2 or and_ln781_23_fu_2191_p2);
    or_ln786_fu_682_p2 <= (and_ln786_fu_676_p2 or and_ln781_fu_647_p2);
    select_ln340_64_fu_2287_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_50_reg_3612(0) = '1') else 
        add_ln415_16_reg_3586;
    select_ln340_65_fu_2373_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_fu_2355_p2(0) = '1') else 
        add_ln703_fu_2329_p2;
    select_ln340_66_fu_2406_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_54_reg_3643(0) = '1') else 
        add_ln415_17_reg_3617;
    select_ln340_67_fu_2660_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_49_fu_2646_p2(0) = '1') else 
        add_ln703_47_reg_3841;
    select_ln340_68_fu_2471_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_58_reg_3674(0) = '1') else 
        add_ln415_18_reg_3648;
    select_ln340_69_fu_2746_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_51_fu_2728_p2(0) = '1') else 
        add_ln703_48_fu_2703_p2;
    select_ln340_70_fu_2500_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_62_reg_3705(0) = '1') else 
        add_ln415_19_reg_3679;
    select_ln340_71_fu_2828_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_53_fu_2814_p2(0) = '1') else 
        add_ln703_49_reg_3897;
    select_ln340_72_fu_2529_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_66_reg_3736(0) = '1') else 
        add_ln415_20_reg_3710;
    select_ln340_73_fu_2914_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_55_fu_2896_p2(0) = '1') else 
        add_ln703_50_fu_2871_p2;
    select_ln340_74_fu_2558_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_70_reg_3767(0) = '1') else 
        add_ln415_21_reg_3741;
    select_ln340_75_fu_2996_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_57_fu_2982_p2(0) = '1') else 
        add_ln703_51_reg_3917;
    select_ln340_76_fu_2587_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_74_reg_3798(0) = '1') else 
        add_ln415_22_reg_3772;
    select_ln340_77_fu_3082_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_59_fu_3064_p2(0) = '1') else 
        add_ln703_52_fu_3039_p2;
    select_ln340_78_fu_2616_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_78_reg_3829(0) = '1') else 
        add_ln415_23_reg_3803;
    select_ln340_79_fu_3164_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_61_fu_3150_p2(0) = '1') else 
        add_ln703_53_reg_3937;
    select_ln340_80_fu_2270_p3 <= 
        select_ln340_fu_2258_p3 when (or_ln340_49_fu_2253_p2(0) = '1') else 
        select_ln388_fu_2264_p3;
    select_ln340_81_fu_2299_p3 <= 
        select_ln340_64_fu_2287_p3 when (or_ln340_52_fu_2282_p2(0) = '1') else 
        select_ln388_32_fu_2293_p3;
    select_ln340_82_fu_2389_p3 <= 
        select_ln340_65_fu_2373_p3 when (or_ln340_53_fu_2367_p2(0) = '1') else 
        select_ln388_33_fu_2381_p3;
    select_ln340_83_fu_2418_p3 <= 
        select_ln340_66_fu_2406_p3 when (or_ln340_56_fu_2401_p2(0) = '1') else 
        select_ln388_34_fu_2412_p3;
    select_ln340_84_fu_2674_p3 <= 
        select_ln340_67_fu_2660_p3 when (or_ln340_57_fu_2655_p2(0) = '1') else 
        select_ln388_35_fu_2667_p3;
    select_ln340_85_fu_2483_p3 <= 
        select_ln340_68_fu_2471_p3 when (or_ln340_60_fu_2466_p2(0) = '1') else 
        select_ln388_36_fu_2477_p3;
    select_ln340_86_fu_2762_p3 <= 
        select_ln340_69_fu_2746_p3 when (or_ln340_61_fu_2740_p2(0) = '1') else 
        select_ln388_37_fu_2754_p3;
    select_ln340_87_fu_2512_p3 <= 
        select_ln340_70_fu_2500_p3 when (or_ln340_64_fu_2495_p2(0) = '1') else 
        select_ln388_38_fu_2506_p3;
    select_ln340_88_fu_2842_p3 <= 
        select_ln340_71_fu_2828_p3 when (or_ln340_65_fu_2823_p2(0) = '1') else 
        select_ln388_39_fu_2835_p3;
    select_ln340_89_fu_2541_p3 <= 
        select_ln340_72_fu_2529_p3 when (or_ln340_68_fu_2524_p2(0) = '1') else 
        select_ln388_40_fu_2535_p3;
    select_ln340_90_fu_2930_p3 <= 
        select_ln340_73_fu_2914_p3 when (or_ln340_69_fu_2908_p2(0) = '1') else 
        select_ln388_41_fu_2922_p3;
    select_ln340_91_fu_2570_p3 <= 
        select_ln340_74_fu_2558_p3 when (or_ln340_72_fu_2553_p2(0) = '1') else 
        select_ln388_42_fu_2564_p3;
    select_ln340_92_fu_3010_p3 <= 
        select_ln340_75_fu_2996_p3 when (or_ln340_73_fu_2991_p2(0) = '1') else 
        select_ln388_43_fu_3003_p3;
    select_ln340_93_fu_2599_p3 <= 
        select_ln340_76_fu_2587_p3 when (or_ln340_76_fu_2582_p2(0) = '1') else 
        select_ln388_44_fu_2593_p3;
    select_ln340_94_fu_3098_p3 <= 
        select_ln340_77_fu_3082_p3 when (or_ln340_77_fu_3076_p2(0) = '1') else 
        select_ln388_45_fu_3090_p3;
    select_ln340_95_fu_2628_p3 <= 
        select_ln340_78_fu_2616_p3 when (or_ln340_80_fu_2611_p2(0) = '1') else 
        select_ln388_46_fu_2622_p3;
    select_ln340_96_fu_3178_p3 <= 
        select_ln340_79_fu_3164_p3 when (or_ln340_81_fu_3159_p2(0) = '1') else 
        select_ln388_47_fu_3171_p3;
    select_ln340_fu_2258_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_reg_3581(0) = '1') else 
        add_ln415_reg_3555;
    select_ln388_32_fu_2293_p3 <= 
        ap_const_lv16_8000 when (and_ln786_50_reg_3607(0) = '1') else 
        add_ln415_16_reg_3586;
    select_ln388_33_fu_2381_p3 <= 
        ap_const_lv16_8000 when (and_ln786_51_fu_2349_p2(0) = '1') else 
        add_ln703_fu_2329_p2;
    select_ln388_34_fu_2412_p3 <= 
        ap_const_lv16_8000 when (and_ln786_53_reg_3638(0) = '1') else 
        add_ln415_17_reg_3617;
    select_ln388_35_fu_2667_p3 <= 
        ap_const_lv16_8000 when (and_ln786_54_fu_2641_p2(0) = '1') else 
        add_ln703_47_reg_3841;
    select_ln388_36_fu_2477_p3 <= 
        ap_const_lv16_8000 when (and_ln786_56_reg_3669(0) = '1') else 
        add_ln415_18_reg_3648;
    select_ln388_37_fu_2754_p3 <= 
        ap_const_lv16_8000 when (and_ln786_57_fu_2722_p2(0) = '1') else 
        add_ln703_48_fu_2703_p2;
    select_ln388_38_fu_2506_p3 <= 
        ap_const_lv16_8000 when (and_ln786_59_reg_3700(0) = '1') else 
        add_ln415_19_reg_3679;
    select_ln388_39_fu_2835_p3 <= 
        ap_const_lv16_8000 when (and_ln786_60_fu_2809_p2(0) = '1') else 
        add_ln703_49_reg_3897;
    select_ln388_40_fu_2535_p3 <= 
        ap_const_lv16_8000 when (and_ln786_62_reg_3731(0) = '1') else 
        add_ln415_20_reg_3710;
    select_ln388_41_fu_2922_p3 <= 
        ap_const_lv16_8000 when (and_ln786_63_fu_2890_p2(0) = '1') else 
        add_ln703_50_fu_2871_p2;
    select_ln388_42_fu_2564_p3 <= 
        ap_const_lv16_8000 when (and_ln786_65_reg_3762(0) = '1') else 
        add_ln415_21_reg_3741;
    select_ln388_43_fu_3003_p3 <= 
        ap_const_lv16_8000 when (and_ln786_66_fu_2977_p2(0) = '1') else 
        add_ln703_51_reg_3917;
    select_ln388_44_fu_2593_p3 <= 
        ap_const_lv16_8000 when (and_ln786_68_reg_3793(0) = '1') else 
        add_ln415_22_reg_3772;
    select_ln388_45_fu_3090_p3 <= 
        ap_const_lv16_8000 when (and_ln786_69_fu_3058_p2(0) = '1') else 
        add_ln703_52_fu_3039_p2;
    select_ln388_46_fu_2622_p3 <= 
        ap_const_lv16_8000 when (and_ln786_71_reg_3824(0) = '1') else 
        add_ln415_23_reg_3803;
    select_ln388_47_fu_3171_p3 <= 
        ap_const_lv16_8000 when (and_ln786_72_fu_3145_p2(0) = '1') else 
        add_ln703_53_reg_3937;
    select_ln388_fu_2264_p3 <= 
        ap_const_lv16_8000 when (and_ln786_48_reg_3576(0) = '1') else 
        add_ln415_reg_3555;
    select_ln416_1_fu_832_p3 <= 
        and_ln779_1_fu_826_p2 when (and_ln416_16_fu_776_p2(0) = '1') else 
        icmp_ln879_3_fu_795_p2;
    select_ln416_2_fu_1025_p3 <= 
        and_ln779_2_fu_1019_p2 when (and_ln416_17_fu_969_p2(0) = '1') else 
        icmp_ln879_5_fu_988_p2;
    select_ln416_3_fu_1218_p3 <= 
        and_ln779_3_fu_1212_p2 when (and_ln416_18_fu_1162_p2(0) = '1') else 
        icmp_ln879_7_fu_1181_p2;
    select_ln416_4_fu_1411_p3 <= 
        and_ln779_4_fu_1405_p2 when (and_ln416_19_fu_1355_p2(0) = '1') else 
        icmp_ln879_9_fu_1374_p2;
    select_ln416_5_fu_1604_p3 <= 
        and_ln779_5_fu_1598_p2 when (and_ln416_20_fu_1548_p2(0) = '1') else 
        icmp_ln879_11_fu_1567_p2;
    select_ln416_6_fu_1797_p3 <= 
        and_ln779_6_fu_1791_p2 when (and_ln416_21_fu_1741_p2(0) = '1') else 
        icmp_ln879_13_fu_1760_p2;
    select_ln416_7_fu_1990_p3 <= 
        and_ln779_7_fu_1984_p2 when (and_ln416_22_fu_1934_p2(0) = '1') else 
        icmp_ln879_15_fu_1953_p2;
    select_ln416_8_fu_2183_p3 <= 
        and_ln779_8_fu_2177_p2 when (and_ln416_23_fu_2127_p2(0) = '1') else 
        icmp_ln879_17_fu_2146_p2;
    select_ln416_fu_639_p3 <= 
        and_ln779_fu_633_p2 when (and_ln416_fu_583_p2(0) = '1') else 
        icmp_ln879_1_fu_602_p2;
    select_ln777_1_fu_805_p3 <= 
        icmp_ln879_3_fu_795_p2 when (and_ln416_16_fu_776_p2(0) = '1') else 
        icmp_ln768_1_fu_800_p2;
    select_ln777_2_fu_998_p3 <= 
        icmp_ln879_5_fu_988_p2 when (and_ln416_17_fu_969_p2(0) = '1') else 
        icmp_ln768_2_fu_993_p2;
    select_ln777_3_fu_1191_p3 <= 
        icmp_ln879_7_fu_1181_p2 when (and_ln416_18_fu_1162_p2(0) = '1') else 
        icmp_ln768_3_fu_1186_p2;
    select_ln777_4_fu_1384_p3 <= 
        icmp_ln879_9_fu_1374_p2 when (and_ln416_19_fu_1355_p2(0) = '1') else 
        icmp_ln768_4_fu_1379_p2;
    select_ln777_5_fu_1577_p3 <= 
        icmp_ln879_11_fu_1567_p2 when (and_ln416_20_fu_1548_p2(0) = '1') else 
        icmp_ln768_5_fu_1572_p2;
    select_ln777_6_fu_1770_p3 <= 
        icmp_ln879_13_fu_1760_p2 when (and_ln416_21_fu_1741_p2(0) = '1') else 
        icmp_ln768_6_fu_1765_p2;
    select_ln777_7_fu_1963_p3 <= 
        icmp_ln879_15_fu_1953_p2 when (and_ln416_22_fu_1934_p2(0) = '1') else 
        icmp_ln768_7_fu_1958_p2;
    select_ln777_8_fu_2156_p3 <= 
        icmp_ln879_17_fu_2146_p2 when (and_ln416_23_fu_2127_p2(0) = '1') else 
        icmp_ln768_8_fu_2151_p2;
    select_ln777_fu_612_p3 <= 
        icmp_ln879_1_fu_602_p2 when (and_ln416_fu_583_p2(0) = '1') else 
        icmp_ln768_fu_607_p2;
        sext_ln703_100_fu_2686_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_85_reg_3854),17));

        sext_ln703_101_fu_2770_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_86_fu_2762_p3),17));

        sext_ln703_102_fu_2774_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_87_reg_3860),17));

        sext_ln703_103_fu_2850_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_88_fu_2842_p3),17));

        sext_ln703_104_fu_2854_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_89_reg_3866_pp0_iter3_reg),17));

        sext_ln703_105_fu_2938_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_90_fu_2930_p3),17));

        sext_ln703_106_fu_2942_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_91_reg_3872_pp0_iter3_reg),17));

        sext_ln703_107_fu_3018_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_92_fu_3010_p3),17));

        sext_ln703_108_fu_3022_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_93_reg_3878_pp0_iter4_reg),17));

        sext_ln703_109_fu_3106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_94_fu_3098_p3),17));

        sext_ln703_110_fu_3110_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_95_reg_3884_pp0_iter4_reg),17));

        sext_ln703_96_fu_2311_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_81_fu_2299_p3),17));

        sext_ln703_97_fu_2426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_82_fu_2389_p3),17));

        sext_ln703_98_fu_2430_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_83_fu_2418_p3),17));

        sext_ln703_99_fu_2682_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_84_fu_2674_p3),17));

        sext_ln703_fu_2307_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_80_fu_2270_p3),17));

    tmp_256_fu_521_p3 <= mul_ln1118_reg_3276(8 downto 8);
    tmp_257_fu_533_p3 <= mul_ln1118_reg_3276(23 downto 23);
    tmp_258_fu_546_p3 <= mul_ln1118_reg_3276(7 downto 7);
    tmp_259_fu_569_p3 <= add_ln415_fu_563_p2(15 downto 15);
    tmp_260_fu_589_p3 <= add_ln415_fu_563_p2(15 downto 15);
    tmp_261_fu_620_p3 <= mul_ln1118_reg_3276(24 downto 24);
    tmp_263_fu_714_p3 <= mul_ln1118_16_reg_3307(8 downto 8);
    tmp_264_fu_726_p3 <= mul_ln1118_16_reg_3307(23 downto 23);
    tmp_265_fu_739_p3 <= mul_ln1118_16_reg_3307(7 downto 7);
    tmp_266_fu_762_p3 <= add_ln415_16_fu_756_p2(15 downto 15);
    tmp_267_fu_782_p3 <= add_ln415_16_fu_756_p2(15 downto 15);
    tmp_268_fu_813_p3 <= mul_ln1118_16_reg_3307(24 downto 24);
    tmp_269_fu_2321_p3 <= add_ln1192_fu_2315_p2(16 downto 16);
    tmp_270_fu_2335_p3 <= add_ln703_fu_2329_p2(15 downto 15);
    tmp_272_fu_907_p3 <= mul_ln1118_17_reg_3338(8 downto 8);
    tmp_273_fu_919_p3 <= mul_ln1118_17_reg_3338(23 downto 23);
    tmp_274_fu_932_p3 <= mul_ln1118_17_reg_3338(7 downto 7);
    tmp_275_fu_955_p3 <= add_ln415_17_fu_949_p2(15 downto 15);
    tmp_276_fu_975_p3 <= add_ln415_17_fu_949_p2(15 downto 15);
    tmp_277_fu_1006_p3 <= mul_ln1118_17_reg_3338(24 downto 24);
    tmp_281_fu_1100_p3 <= mul_ln1118_18_reg_3369(8 downto 8);
    tmp_282_fu_1112_p3 <= mul_ln1118_18_reg_3369(23 downto 23);
    tmp_283_fu_1125_p3 <= mul_ln1118_18_reg_3369(7 downto 7);
    tmp_284_fu_1148_p3 <= add_ln415_18_fu_1142_p2(15 downto 15);
    tmp_285_fu_1168_p3 <= add_ln415_18_fu_1142_p2(15 downto 15);
    tmp_286_fu_1199_p3 <= mul_ln1118_18_reg_3369(24 downto 24);
    tmp_287_fu_2695_p3 <= add_ln1192_65_fu_2689_p2(16 downto 16);
    tmp_288_fu_2708_p3 <= add_ln703_48_fu_2703_p2(15 downto 15);
    tmp_290_fu_1293_p3 <= mul_ln1118_19_reg_3400(8 downto 8);
    tmp_291_fu_1305_p3 <= mul_ln1118_19_reg_3400(23 downto 23);
    tmp_292_fu_1318_p3 <= mul_ln1118_19_reg_3400(7 downto 7);
    tmp_293_fu_1341_p3 <= add_ln415_19_fu_1335_p2(15 downto 15);
    tmp_294_fu_1361_p3 <= add_ln415_19_fu_1335_p2(15 downto 15);
    tmp_295_fu_1392_p3 <= mul_ln1118_19_reg_3400(24 downto 24);
    tmp_299_fu_1486_p3 <= mul_ln1118_20_reg_3431(8 downto 8);
    tmp_300_fu_1498_p3 <= mul_ln1118_20_reg_3431(23 downto 23);
    tmp_301_fu_1511_p3 <= mul_ln1118_20_reg_3431(7 downto 7);
    tmp_302_fu_1534_p3 <= add_ln415_20_fu_1528_p2(15 downto 15);
    tmp_303_fu_1554_p3 <= add_ln415_20_fu_1528_p2(15 downto 15);
    tmp_304_fu_1585_p3 <= mul_ln1118_20_reg_3431(24 downto 24);
    tmp_305_fu_2863_p3 <= add_ln1192_67_fu_2857_p2(16 downto 16);
    tmp_306_fu_2876_p3 <= add_ln703_50_fu_2871_p2(15 downto 15);
    tmp_308_fu_1679_p3 <= mul_ln1118_21_reg_3462(8 downto 8);
    tmp_309_fu_1691_p3 <= mul_ln1118_21_reg_3462(23 downto 23);
    tmp_310_fu_1704_p3 <= mul_ln1118_21_reg_3462(7 downto 7);
    tmp_311_fu_1727_p3 <= add_ln415_21_fu_1721_p2(15 downto 15);
    tmp_312_fu_1747_p3 <= add_ln415_21_fu_1721_p2(15 downto 15);
    tmp_313_fu_1778_p3 <= mul_ln1118_21_reg_3462(24 downto 24);
    tmp_317_fu_1872_p3 <= mul_ln1118_22_reg_3493(8 downto 8);
    tmp_318_fu_1884_p3 <= mul_ln1118_22_reg_3493(23 downto 23);
    tmp_319_fu_1897_p3 <= mul_ln1118_22_reg_3493(7 downto 7);
    tmp_320_fu_1920_p3 <= add_ln415_22_fu_1914_p2(15 downto 15);
    tmp_321_fu_1940_p3 <= add_ln415_22_fu_1914_p2(15 downto 15);
    tmp_322_fu_1971_p3 <= mul_ln1118_22_reg_3493(24 downto 24);
    tmp_323_fu_3031_p3 <= add_ln1192_69_fu_3025_p2(16 downto 16);
    tmp_324_fu_3044_p3 <= add_ln703_52_fu_3039_p2(15 downto 15);
    tmp_326_fu_2065_p3 <= mul_ln1118_23_reg_3524(8 downto 8);
    tmp_327_fu_2077_p3 <= mul_ln1118_23_reg_3524(23 downto 23);
    tmp_328_fu_2090_p3 <= mul_ln1118_23_reg_3524(7 downto 7);
    tmp_329_fu_2113_p3 <= add_ln415_23_fu_2107_p2(15 downto 15);
    tmp_330_fu_2133_p3 <= add_ln415_23_fu_2107_p2(15 downto 15);
    tmp_331_fu_2164_p3 <= mul_ln1118_23_reg_3524(24 downto 24);
    trunc_ln4_fu_512_p4 <= mul_ln1118_reg_3276(23 downto 8);
    trunc_ln708_15_fu_898_p4 <= mul_ln1118_17_reg_3338(23 downto 8);
    trunc_ln708_16_fu_1091_p4 <= mul_ln1118_18_reg_3369(23 downto 8);
    trunc_ln708_17_fu_1284_p4 <= mul_ln1118_19_reg_3400(23 downto 8);
    trunc_ln708_18_fu_1477_p4 <= mul_ln1118_20_reg_3431(23 downto 8);
    trunc_ln708_19_fu_1670_p4 <= mul_ln1118_21_reg_3462(23 downto 8);
    trunc_ln708_20_fu_1863_p4 <= mul_ln1118_22_reg_3493(23 downto 8);
    trunc_ln708_21_fu_2056_p4 <= mul_ln1118_23_reg_3524(23 downto 8);
    trunc_ln708_s_fu_705_p4 <= mul_ln1118_16_reg_3307(23 downto 8);
    trunc_ln718_16_fu_239_p1 <= mul_ln1118_16_fu_3196_p2(7 - 1 downto 0);
    trunc_ln718_17_fu_275_p1 <= mul_ln1118_17_fu_3206_p2(7 - 1 downto 0);
    trunc_ln718_18_fu_311_p1 <= mul_ln1118_18_fu_3216_p2(7 - 1 downto 0);
    trunc_ln718_19_fu_347_p1 <= mul_ln1118_19_fu_3226_p2(7 - 1 downto 0);
    trunc_ln718_20_fu_383_p1 <= mul_ln1118_20_fu_3236_p2(7 - 1 downto 0);
    trunc_ln718_21_fu_419_p1 <= mul_ln1118_21_fu_3246_p2(7 - 1 downto 0);
    trunc_ln718_22_fu_455_p1 <= mul_ln1118_22_fu_3256_p2(7 - 1 downto 0);
    trunc_ln718_23_fu_491_p1 <= mul_ln1118_23_fu_3266_p2(7 - 1 downto 0);
    trunc_ln718_fu_203_p1 <= mul_ln1118_fu_3186_p2(7 - 1 downto 0);
    xor_ln340_48_fu_2361_p2 <= (tmp_269_fu_2321_p3 xor ap_const_lv1_1);
    xor_ln340_49_fu_2646_p2 <= (tmp_279_reg_3847 xor tmp_278_reg_3834);
    xor_ln340_50_fu_2650_p2 <= (tmp_278_reg_3834 xor ap_const_lv1_1);
    xor_ln340_51_fu_2728_p2 <= (tmp_288_fu_2708_p3 xor tmp_287_fu_2695_p3);
    xor_ln340_52_fu_2734_p2 <= (tmp_287_fu_2695_p3 xor ap_const_lv1_1);
    xor_ln340_53_fu_2814_p2 <= (tmp_297_reg_3903 xor tmp_296_reg_3890);
    xor_ln340_54_fu_2818_p2 <= (tmp_296_reg_3890 xor ap_const_lv1_1);
    xor_ln340_55_fu_2896_p2 <= (tmp_306_fu_2876_p3 xor tmp_305_fu_2863_p3);
    xor_ln340_56_fu_2902_p2 <= (tmp_305_fu_2863_p3 xor ap_const_lv1_1);
    xor_ln340_57_fu_2982_p2 <= (tmp_315_reg_3923 xor tmp_314_reg_3910);
    xor_ln340_58_fu_2986_p2 <= (tmp_314_reg_3910 xor ap_const_lv1_1);
    xor_ln340_59_fu_3064_p2 <= (tmp_324_fu_3044_p3 xor tmp_323_fu_3031_p3);
    xor_ln340_60_fu_3070_p2 <= (tmp_323_fu_3031_p3 xor ap_const_lv1_1);
    xor_ln340_61_fu_3150_p2 <= (tmp_333_reg_3943 xor tmp_332_reg_3930);
    xor_ln340_62_fu_3154_p2 <= (tmp_332_reg_3930 xor ap_const_lv1_1);
    xor_ln340_fu_2355_p2 <= (tmp_270_fu_2335_p3 xor tmp_269_fu_2321_p3);
    xor_ln416_47_fu_770_p2 <= (tmp_266_fu_762_p3 xor ap_const_lv1_1);
    xor_ln416_48_fu_963_p2 <= (tmp_275_fu_955_p3 xor ap_const_lv1_1);
    xor_ln416_49_fu_1156_p2 <= (tmp_284_fu_1148_p3 xor ap_const_lv1_1);
    xor_ln416_50_fu_1349_p2 <= (tmp_293_fu_1341_p3 xor ap_const_lv1_1);
    xor_ln416_51_fu_1542_p2 <= (tmp_302_fu_1534_p3 xor ap_const_lv1_1);
    xor_ln416_52_fu_1735_p2 <= (tmp_311_fu_1727_p3 xor ap_const_lv1_1);
    xor_ln416_53_fu_1928_p2 <= (tmp_320_fu_1920_p3 xor ap_const_lv1_1);
    xor_ln416_54_fu_2121_p2 <= (tmp_329_fu_2113_p3 xor ap_const_lv1_1);
    xor_ln416_fu_577_p2 <= (tmp_259_fu_569_p3 xor ap_const_lv1_1);
    xor_ln779_16_fu_820_p2 <= (tmp_268_fu_813_p3 xor ap_const_lv1_1);
    xor_ln779_17_fu_1013_p2 <= (tmp_277_fu_1006_p3 xor ap_const_lv1_1);
    xor_ln779_18_fu_1206_p2 <= (tmp_286_fu_1199_p3 xor ap_const_lv1_1);
    xor_ln779_19_fu_1399_p2 <= (tmp_295_fu_1392_p3 xor ap_const_lv1_1);
    xor_ln779_20_fu_1592_p2 <= (tmp_304_fu_1585_p3 xor ap_const_lv1_1);
    xor_ln779_21_fu_1785_p2 <= (tmp_313_fu_1778_p3 xor ap_const_lv1_1);
    xor_ln779_22_fu_1978_p2 <= (tmp_322_fu_1971_p3 xor ap_const_lv1_1);
    xor_ln779_23_fu_2171_p2 <= (tmp_331_fu_2164_p3 xor ap_const_lv1_1);
    xor_ln779_fu_627_p2 <= (tmp_261_fu_620_p3 xor ap_const_lv1_1);
    xor_ln785_16_fu_665_p2 <= (tmp_reg_3285 xor ap_const_lv1_1);
    xor_ln785_17_fu_846_p2 <= (select_ln777_1_fu_805_p3 xor ap_const_lv1_1);
    xor_ln785_18_fu_858_p2 <= (tmp_262_reg_3316 xor ap_const_lv1_1);
    xor_ln785_19_fu_1039_p2 <= (select_ln777_2_fu_998_p3 xor ap_const_lv1_1);
    xor_ln785_20_fu_1051_p2 <= (tmp_271_reg_3347 xor ap_const_lv1_1);
    xor_ln785_21_fu_1232_p2 <= (select_ln777_3_fu_1191_p3 xor ap_const_lv1_1);
    xor_ln785_22_fu_1244_p2 <= (tmp_280_reg_3378 xor ap_const_lv1_1);
    xor_ln785_23_fu_1425_p2 <= (select_ln777_4_fu_1384_p3 xor ap_const_lv1_1);
    xor_ln785_24_fu_1437_p2 <= (tmp_289_reg_3409 xor ap_const_lv1_1);
    xor_ln785_25_fu_1618_p2 <= (select_ln777_5_fu_1577_p3 xor ap_const_lv1_1);
    xor_ln785_26_fu_1630_p2 <= (tmp_298_reg_3440 xor ap_const_lv1_1);
    xor_ln785_27_fu_1811_p2 <= (select_ln777_6_fu_1770_p3 xor ap_const_lv1_1);
    xor_ln785_28_fu_1823_p2 <= (tmp_307_reg_3471 xor ap_const_lv1_1);
    xor_ln785_29_fu_2004_p2 <= (select_ln777_7_fu_1963_p3 xor ap_const_lv1_1);
    xor_ln785_30_fu_2016_p2 <= (tmp_316_reg_3502 xor ap_const_lv1_1);
    xor_ln785_31_fu_2197_p2 <= (select_ln777_8_fu_2156_p3 xor ap_const_lv1_1);
    xor_ln785_32_fu_2209_p2 <= (tmp_325_reg_3533 xor ap_const_lv1_1);
    xor_ln785_fu_653_p2 <= (select_ln777_fu_612_p3 xor ap_const_lv1_1);
    xor_ln786_32_fu_881_p2 <= (or_ln786_32_fu_875_p2 xor ap_const_lv1_1);
    xor_ln786_33_fu_2343_p2 <= (tmp_270_fu_2335_p3 xor ap_const_lv1_1);
    xor_ln786_34_fu_1074_p2 <= (or_ln786_33_fu_1068_p2 xor ap_const_lv1_1);
    xor_ln786_35_fu_2636_p2 <= (tmp_279_reg_3847 xor ap_const_lv1_1);
    xor_ln786_36_fu_1267_p2 <= (or_ln786_34_fu_1261_p2 xor ap_const_lv1_1);
    xor_ln786_37_fu_2716_p2 <= (tmp_288_fu_2708_p3 xor ap_const_lv1_1);
    xor_ln786_38_fu_1460_p2 <= (or_ln786_35_fu_1454_p2 xor ap_const_lv1_1);
    xor_ln786_39_fu_2804_p2 <= (tmp_297_reg_3903 xor ap_const_lv1_1);
    xor_ln786_40_fu_1653_p2 <= (or_ln786_36_fu_1647_p2 xor ap_const_lv1_1);
    xor_ln786_41_fu_2884_p2 <= (tmp_306_fu_2876_p3 xor ap_const_lv1_1);
    xor_ln786_42_fu_1846_p2 <= (or_ln786_37_fu_1840_p2 xor ap_const_lv1_1);
    xor_ln786_43_fu_2972_p2 <= (tmp_315_reg_3923 xor ap_const_lv1_1);
    xor_ln786_44_fu_2039_p2 <= (or_ln786_38_fu_2033_p2 xor ap_const_lv1_1);
    xor_ln786_45_fu_3052_p2 <= (tmp_324_fu_3044_p3 xor ap_const_lv1_1);
    xor_ln786_46_fu_2232_p2 <= (or_ln786_39_fu_2226_p2 xor ap_const_lv1_1);
    xor_ln786_47_fu_3140_p2 <= (tmp_333_reg_3943 xor ap_const_lv1_1);
    xor_ln786_fu_688_p2 <= (or_ln786_fu_682_p2 xor ap_const_lv1_1);
    zext_ln415_16_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_16_fu_746_p2),16));
    zext_ln415_17_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_17_fu_939_p2),16));
    zext_ln415_18_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_18_fu_1132_p2),16));
    zext_ln415_19_fu_1331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_19_fu_1325_p2),16));
    zext_ln415_20_fu_1524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_20_fu_1518_p2),16));
    zext_ln415_21_fu_1717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_21_fu_1711_p2),16));
    zext_ln415_22_fu_1910_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_22_fu_1904_p2),16));
    zext_ln415_23_fu_2103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_23_fu_2097_p2),16));
    zext_ln415_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln415_fu_553_p2),16));
end behav;
