# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xavier/MSc_Project/git_v/Tiny_YOLO_v3_ZYNQ/sw/Tiny_Yolo_v3/Tiny_Yolo_v3.srcs/sources_1/bd/yolo_sys/ip/yolo_sys_processing_system7_0_0/yolo_sys_processing_system7_0_0.xci
# IP: The module: 'yolo_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xavier/MSc_Project/git_v/Tiny_YOLO_v3_ZYNQ/sw/Tiny_Yolo_v3/Tiny_Yolo_v3.srcs/sources_1/bd/yolo_sys/ip/yolo_sys_processing_system7_0_0/yolo_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yolo_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/xavier/MSc_Project/git_v/Tiny_YOLO_v3_ZYNQ/sw/Tiny_Yolo_v3/Tiny_Yolo_v3.srcs/sources_1/bd/yolo_sys/ip/yolo_sys_processing_system7_0_0/yolo_sys_processing_system7_0_0.xci
# IP: The module: 'yolo_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xavier/MSc_Project/git_v/Tiny_YOLO_v3_ZYNQ/sw/Tiny_Yolo_v3/Tiny_Yolo_v3.srcs/sources_1/bd/yolo_sys/ip/yolo_sys_processing_system7_0_0/yolo_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yolo_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
