#ifndef LAYER_PARAMETER_H
#define LAYER_PARAMETER_H

#define YOLO_FOLD_TOTAL_CHANNEL ((255+3)/4)
#define MAX_KERNEL_NUM 32
#define YOLO_INPUT_HEIGHT 13
#define YOLO_INPUT_WIDTH 13
#define MAX_FOLD_CH_BIT (5-2+1)
#endif
