#ifndef LAYER_PARAMETER_H
#define LAYER_PARAMETER_H

#define CONV_KERNEL_DIM 3
#define CONV_PAD 1
#define CONV_INPUT_CHANNEL 3
#define CONV_INPUT_WIDTH (416+2*CONV_PAD)
#define CONV_INPUT_HEIGHT (416+2*CONV_PAD)
#define CONV_OUTPUT_CHANNEL 16
#define CONV_OUTPUT_WIDTH 416
#define CONV_OUTPUT_HEIGHT 416
#define CONV_LEAKY 1
#define CONV_REAL_INPUT_HEIGHT (416+2*CONV_PAD)

#define POOL_KERNEL_DIM 2
#define POOL_STRIDE 2//1
#define POOL_IN_PAD (POOL_KERNEL_DIM-1)
#define POOL_OUT_PAD 0//1
#define POOL_INPUT_CHANNEL 16//512
#define POOL_INPUT_WIDTH (416+2*POOL_IN_PAD)//13
#define POOL_INPUT_HEIGHT (416+2*POOL_IN_PAD)
#define POOL_OUTPUT_CHANNEL POOL_INPUT_CHANNEL
#define POOL_OUTPUT_WIDTH ((POOL_INPUT_WIDTH-POOL_IN_PAD-POOL_KERNEL_DIM)/POOL_STRIDE+1)
#define POOL_OUTPUT_HEIGHT ((POOL_INPUT_HEIGHT-POOL_IN_PAD-POOL_KERNEL_DIM)/POOL_STRIDE+1)

#endif
