#ifndef LAYER_PARAMETER_H
#define LAYER_PARAMETER_H

#define KERNEL_DIM 2
#define STRIDE 2//1
#define PAD (KERNEL_DIM-1)
#define POOL_PAD 0//1
#define INPUT_CHANNEL 16//512
#define INPUT_WIDTH (416+2*PAD)//13
#define INPUT_HEIGHT (416+2*PAD)
#define OUTPUT_CHANNEL INPUT_CHANNEL
#define OUTPUT_WIDTH ((INPUT_WIDTH-PAD-KERNEL_DIM)/STRIDE+1)
#define OUTPUT_HEIGHT ((INPUT_HEIGHT-PAD-KERNEL_DIM)/STRIDE+1)

#define WINDOW_AREA KERNEL_DIM*KERNEL_DIM
#define KERNEL_AREA WINDOW_AREA*INPUT_CHANNEL
#define KERNEL_NUM OUTPUT_CHANNEL //should be equal to or smaller than OUTPUT_CHANNEL
								  //depend on resource available

#define STREAM_TX_SIZE ((KERNEL_NUM-1)/INPUT_CHANNEL+1)

#endif
