// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module out_stream_merge (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_group_13_V_V_dout,
        out_stream_group_13_V_V_empty_n,
        out_stream_group_13_V_V_read,
        out_stream_group_5_V_V_dout,
        out_stream_group_5_V_V_empty_n,
        out_stream_group_5_V_V_read,
        out_stream_group_14_V_V_dout,
        out_stream_group_14_V_V_empty_n,
        out_stream_group_14_V_V_read,
        out_stream_group_6_V_V_dout,
        out_stream_group_6_V_V_empty_n,
        out_stream_group_6_V_V_read,
        out_stream_group_15_V_V_dout,
        out_stream_group_15_V_V_empty_n,
        out_stream_group_15_V_V_read,
        out_stream_group_7_V_V_dout,
        out_stream_group_7_V_V_empty_n,
        out_stream_group_7_V_V_read,
        outStream_TREADY,
        ap_ce,
        out_stream_group_0_V_V_dout,
        out_stream_group_0_V_V_empty_n,
        out_stream_group_0_V_V_read,
        out_stream_group_1_V_V_dout,
        out_stream_group_1_V_V_empty_n,
        out_stream_group_1_V_V_read,
        out_stream_group_2_V_V_dout,
        out_stream_group_2_V_V_empty_n,
        out_stream_group_2_V_V_read,
        out_stream_group_3_V_V_dout,
        out_stream_group_3_V_V_empty_n,
        out_stream_group_3_V_V_read,
        out_stream_group_4_V_V_dout,
        out_stream_group_4_V_V_empty_n,
        out_stream_group_4_V_V_read,
        out_stream_group_8_V_V_dout,
        out_stream_group_8_V_V_empty_n,
        out_stream_group_8_V_V_read,
        out_stream_group_9_V_V_dout,
        out_stream_group_9_V_V_empty_n,
        out_stream_group_9_V_V_read,
        out_stream_group_10_V_V_dout,
        out_stream_group_10_V_V_empty_n,
        out_stream_group_10_V_V_read,
        out_stream_group_11_V_V_dout,
        out_stream_group_11_V_V_empty_n,
        out_stream_group_11_V_V_read,
        out_stream_group_12_V_V_dout,
        out_stream_group_12_V_V_empty_n,
        out_stream_group_12_V_V_read,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        input_ch_idx,
        curr_input_keep_V,
        curr_input_strb_V,
        curr_input_user_V,
        curr_input_id_V,
        curr_input_dest_V,
        last_V,
        out_stream_group_0_V_V_blk_n,
        out_stream_group_1_V_V_blk_n,
        out_stream_group_2_V_V_blk_n,
        out_stream_group_3_V_V_blk_n,
        out_stream_group_4_V_V_blk_n,
        out_stream_group_5_V_V_blk_n,
        out_stream_group_6_V_V_blk_n,
        out_stream_group_7_V_V_blk_n,
        out_stream_group_8_V_V_blk_n,
        out_stream_group_9_V_V_blk_n,
        out_stream_group_10_V_V_blk_n,
        out_stream_group_11_V_V_blk_n,
        out_stream_group_12_V_V_blk_n,
        out_stream_group_13_V_V_blk_n,
        out_stream_group_14_V_V_blk_n,
        out_stream_group_15_V_V_blk_n,
        outStream_TDATA_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] out_stream_group_13_V_V_dout;
input   out_stream_group_13_V_V_empty_n;
output   out_stream_group_13_V_V_read;
input  [15:0] out_stream_group_5_V_V_dout;
input   out_stream_group_5_V_V_empty_n;
output   out_stream_group_5_V_V_read;
input  [15:0] out_stream_group_14_V_V_dout;
input   out_stream_group_14_V_V_empty_n;
output   out_stream_group_14_V_V_read;
input  [15:0] out_stream_group_6_V_V_dout;
input   out_stream_group_6_V_V_empty_n;
output   out_stream_group_6_V_V_read;
input  [15:0] out_stream_group_15_V_V_dout;
input   out_stream_group_15_V_V_empty_n;
output   out_stream_group_15_V_V_read;
input  [15:0] out_stream_group_7_V_V_dout;
input   out_stream_group_7_V_V_empty_n;
output   out_stream_group_7_V_V_read;
input   outStream_TREADY;
input   ap_ce;
input  [15:0] out_stream_group_0_V_V_dout;
input   out_stream_group_0_V_V_empty_n;
output   out_stream_group_0_V_V_read;
input  [15:0] out_stream_group_1_V_V_dout;
input   out_stream_group_1_V_V_empty_n;
output   out_stream_group_1_V_V_read;
input  [15:0] out_stream_group_2_V_V_dout;
input   out_stream_group_2_V_V_empty_n;
output   out_stream_group_2_V_V_read;
input  [15:0] out_stream_group_3_V_V_dout;
input   out_stream_group_3_V_V_empty_n;
output   out_stream_group_3_V_V_read;
input  [15:0] out_stream_group_4_V_V_dout;
input   out_stream_group_4_V_V_empty_n;
output   out_stream_group_4_V_V_read;
input  [15:0] out_stream_group_8_V_V_dout;
input   out_stream_group_8_V_V_empty_n;
output   out_stream_group_8_V_V_read;
input  [15:0] out_stream_group_9_V_V_dout;
input   out_stream_group_9_V_V_empty_n;
output   out_stream_group_9_V_V_read;
input  [15:0] out_stream_group_10_V_V_dout;
input   out_stream_group_10_V_V_empty_n;
output   out_stream_group_10_V_V_read;
input  [15:0] out_stream_group_11_V_V_dout;
input   out_stream_group_11_V_V_empty_n;
output   out_stream_group_11_V_V_read;
input  [15:0] out_stream_group_12_V_V_dout;
input   out_stream_group_12_V_V_empty_n;
output   out_stream_group_12_V_V_read;
output  [31:0] outStream_TDATA;
output   outStream_TVALID;
output  [3:0] outStream_TKEEP;
output  [3:0] outStream_TSTRB;
output  [1:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [4:0] outStream_TID;
output  [5:0] outStream_TDEST;
input  [1:0] input_ch_idx;
input  [3:0] curr_input_keep_V;
input  [3:0] curr_input_strb_V;
input  [1:0] curr_input_user_V;
input  [4:0] curr_input_id_V;
input  [5:0] curr_input_dest_V;
input  [0:0] last_V;
output   out_stream_group_0_V_V_blk_n;
output   out_stream_group_1_V_V_blk_n;
output   out_stream_group_2_V_V_blk_n;
output   out_stream_group_3_V_V_blk_n;
output   out_stream_group_4_V_V_blk_n;
output   out_stream_group_5_V_V_blk_n;
output   out_stream_group_6_V_V_blk_n;
output   out_stream_group_7_V_V_blk_n;
output   out_stream_group_8_V_V_blk_n;
output   out_stream_group_9_V_V_blk_n;
output   out_stream_group_10_V_V_blk_n;
output   out_stream_group_11_V_V_blk_n;
output   out_stream_group_12_V_V_blk_n;
output   out_stream_group_13_V_V_blk_n;
output   out_stream_group_14_V_V_blk_n;
output   out_stream_group_15_V_V_blk_n;
output   outStream_TDATA_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_stream_group_13_V_V_read;
reg out_stream_group_5_V_V_read;
reg out_stream_group_14_V_V_read;
reg out_stream_group_6_V_V_read;
reg out_stream_group_15_V_V_read;
reg out_stream_group_7_V_V_read;
reg out_stream_group_0_V_V_read;
reg out_stream_group_1_V_V_read;
reg out_stream_group_2_V_V_read;
reg out_stream_group_3_V_V_read;
reg out_stream_group_4_V_V_read;
reg out_stream_group_8_V_V_read;
reg out_stream_group_9_V_V_read;
reg out_stream_group_10_V_V_read;
reg out_stream_group_11_V_V_read;
reg out_stream_group_12_V_V_read;
reg[31:0] outStream_TDATA;
reg outStream_TVALID;
reg[3:0] outStream_TKEEP;
reg[3:0] outStream_TSTRB;
reg[1:0] outStream_TUSER;
reg[0:0] outStream_TLAST;
reg[4:0] outStream_TID;
reg[5:0] outStream_TDEST;
reg out_stream_group_0_V_V_blk_n;
reg out_stream_group_1_V_V_blk_n;
reg out_stream_group_2_V_V_blk_n;
reg out_stream_group_3_V_V_blk_n;
reg out_stream_group_4_V_V_blk_n;
reg out_stream_group_5_V_V_blk_n;
reg out_stream_group_6_V_V_blk_n;
reg out_stream_group_7_V_V_blk_n;
reg out_stream_group_8_V_V_blk_n;
reg out_stream_group_9_V_V_blk_n;
reg out_stream_group_10_V_V_blk_n;
reg out_stream_group_11_V_V_blk_n;
reg out_stream_group_12_V_V_blk_n;
reg out_stream_group_13_V_V_blk_n;
reg out_stream_group_14_V_V_blk_n;
reg out_stream_group_15_V_V_blk_n;
reg outStream_TDATA_blk_n;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] phi_ln114_4_reg_500;
reg   [0:0] icmp_ln114_5_reg_899;
reg   [0:0] phi_ln114_5_reg_559;
reg    ap_predicate_op129_read_state4;
reg    ap_predicate_op131_read_state4;
reg   [0:0] icmp_ln114_6_reg_856;
reg   [0:0] phi_ln114_6_reg_510;
reg    ap_predicate_op137_read_state4;
reg    ap_predicate_op139_read_state4;
reg   [0:0] icmp_ln114_7_reg_913;
reg   [0:0] phi_ln114_7_reg_569;
reg    ap_predicate_op141_read_state4;
reg    ap_predicate_op143_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln114_reg_814;
reg   [0:0] phi_ln114_reg_427;
reg   [0:0] icmp_ln114_1_reg_818;
reg   [0:0] phi_ln114_1_reg_439;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] icmp_ln114_2_reg_822;
reg   [0:0] phi_ln114_2_reg_478;
reg   [0:0] icmp_ln114_3_reg_895;
reg   [0:0] phi_ln114_3_reg_488;
reg   [0:0] icmp_ln114_4_reg_836;
wire    ap_block_pp0_stage3;
wire   [3:0] shl_ln1_fu_659_p3;
reg   [3:0] shl_ln1_reg_808;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln114_fu_667_p2;
wire   [0:0] icmp_ln114_1_fu_679_p2;
reg   [0:0] ap_phi_mux_phi_ln114_phi_fu_430_p4;
wire   [0:0] icmp_ln114_2_fu_691_p2;
wire   [0:0] tmp_17_nbreadreq_fu_168_p3;
wire   [0:0] tmp_16_nbreadreq_fu_176_p3;
wire   [0:0] icmp_ln114_4_fu_703_p2;
wire   [0:0] tmp_19_nbreadreq_fu_184_p3;
wire   [0:0] tmp_18_nbreadreq_fu_192_p3;
wire   [2:0] or_ln228_fu_709_p2;
reg   [2:0] or_ln228_reg_850;
wire   [0:0] icmp_ln114_6_fu_715_p2;
wire   [0:0] tmp_21_nbreadreq_fu_200_p3;
wire   [0:0] tmp_20_nbreadreq_fu_208_p3;
reg   [5:0] tmp_dest_V_reg_870;
reg    ap_predicate_op52_read_state2;
reg    ap_predicate_op54_read_state2;
reg    ap_predicate_op57_read_state2;
reg    ap_predicate_op59_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage1_11001;
reg   [4:0] tmp_id_V_reg_875;
reg   [1:0] tmp_user_V_reg_880;
reg   [3:0] tmp_strb_V_reg_885;
reg   [3:0] tmp_keep_V_reg_890;
wire   [0:0] icmp_ln114_3_fu_735_p2;
wire   [0:0] ap_phi_mux_phi_ln114_2_phi_fu_481_p4;
wire   [0:0] icmp_ln114_5_fu_746_p2;
wire   [0:0] ap_phi_mux_phi_ln114_4_phi_fu_503_p4;
wire   [0:0] tmp_1_5_nbreadreq_fu_317_p3;
wire   [0:0] tmp_1_4_nbreadreq_fu_325_p3;
wire   [0:0] icmp_ln114_7_fu_765_p2;
wire   [0:0] ap_phi_mux_phi_ln114_6_phi_fu_513_p4;
wire   [0:0] tmp_1_7_nbreadreq_fu_333_p3;
wire   [0:0] tmp_1_6_nbreadreq_fu_341_p3;
wire   [0:0] icmp_ln251_fu_771_p2;
reg   [0:0] icmp_ln251_reg_927;
reg    ap_predicate_op100_read_state3;
reg    ap_predicate_op102_read_state3;
reg    ap_predicate_op106_read_state3;
reg    ap_predicate_op108_read_state3;
reg    ap_predicate_op114_read_state3;
reg    ap_predicate_op116_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] tmp_last_V_fu_794_p2;
reg   [0:0] tmp_last_V_reg_962;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage3_subdone;
reg   [3:0] ap_port_reg_curr_input_keep_V;
reg   [3:0] ap_port_reg_curr_input_strb_V;
reg   [1:0] ap_port_reg_curr_input_user_V;
reg   [4:0] ap_port_reg_curr_input_id_V;
reg   [5:0] ap_port_reg_curr_input_dest_V;
reg   [0:0] ap_port_reg_last_V;
wire   [0:0] tmp_s_nbreadreq_fu_144_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_reg_427;
wire   [0:0] tmp_15_nbreadreq_fu_136_p3;
wire   [0:0] tmp_1_s_nbreadreq_fu_160_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_1_reg_439;
wire   [0:0] tmp_1_1_nbreadreq_fu_152_p3;
reg   [15:0] ap_phi_mux_tmp_V_load_phi_fu_454_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_V_load_reg_451;
reg   [15:0] ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_2_0_reg_462;
reg   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_2_reg_478;
wire   [0:0] tmp_1_2_nbreadreq_fu_309_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_3_reg_488;
wire   [0:0] tmp_1_3_nbreadreq_fu_301_p3;
reg   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_4_reg_500;
reg   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_6_reg_510;
reg   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_4_0_reg_520;
reg   [15:0] ap_phi_mux_tmp_V_load_1_phi_fu_536_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_V_load_1_reg_533;
reg   [15:0] ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_2_1_reg_544;
reg   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_5_reg_559;
reg   [0:0] ap_phi_reg_pp0_iter0_phi_ln114_7_reg_569;
reg   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_4_1_reg_579;
reg   [15:0] ap_phi_reg_pp0_iter0_tmp_V_load_2_reg_591;
reg   [15:0] ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_2_2_reg_600;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_4_2_reg_615;
reg   [15:0] ap_phi_reg_pp0_iter1_curr_output_0_1_4_2_reg_615;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_V_load_3_reg_626;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_V_load_3_reg_626;
reg   [15:0] ap_phi_mux_curr_output_0_1_2_3_phi_fu_638_p6;
reg   [15:0] ap_phi_reg_pp0_iter1_curr_output_0_1_2_3_reg_635;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_0_1_2_3_reg_635;
wire   [31:0] tmp_data_fu_721_p3;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] tmp_data_1_fu_776_p3;
reg    ap_block_pp0_stage2_01001;
wire   [31:0] tmp_data_2_fu_785_p3;
reg    ap_block_pp0_stage3_01001;
wire   [31:0] tmp_data_3_fu_799_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln228_fu_647_p1;
wire   [3:0] or_ln114_fu_673_p2;
wire   [3:0] or_ln114_1_fu_685_p2;
wire   [3:0] or_ln114_3_fu_697_p2;
wire   [2:0] shl_ln_fu_651_p3;
wire   [3:0] or_ln114_2_fu_730_p2;
wire   [3:0] or_ln114_4_fu_741_p2;
wire   [3:0] shl_ln2_fu_752_p3;
wire   [3:0] or_ln114_5_fu_759_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
reg    ap_condition_874;
reg    ap_condition_295;
reg    ap_condition_297;
reg    ap_condition_28;
reg    ap_condition_294;
reg    ap_condition_601;
reg    ap_condition_535;
reg    ap_condition_830;
reg    ap_condition_834;
reg    ap_condition_905;
reg    ap_condition_111;
reg    ap_condition_123;
reg    ap_condition_144;
reg    ap_condition_916;
reg    ap_condition_920;
reg    ap_condition_923;
reg    ap_condition_928;
reg    ap_condition_566;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_601)) begin
        if ((phi_ln114_2_reg_478 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_curr_output_0_1_4_1_reg_579 <= ap_phi_reg_pp0_iter0_curr_output_0_1_4_0_reg_520;
        end else if ((phi_ln114_2_reg_478 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_curr_output_0_1_4_1_reg_579 <= ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_535)) begin
        if ((icmp_ln114_2_fu_691_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_2_reg_478 <= tmp_17_nbreadreq_fu_168_p3;
        end else if ((icmp_ln114_2_fu_691_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_2_reg_478 <= tmp_16_nbreadreq_fu_176_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_535)) begin
        if ((icmp_ln114_4_fu_703_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_4_reg_500 <= tmp_19_nbreadreq_fu_184_p3;
        end else if ((icmp_ln114_4_fu_703_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_4_reg_500 <= tmp_18_nbreadreq_fu_192_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_830)) begin
        if ((icmp_ln114_5_fu_746_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_5_reg_559 <= tmp_1_5_nbreadreq_fu_317_p3;
        end else if ((icmp_ln114_5_fu_746_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_5_reg_559 <= tmp_1_4_nbreadreq_fu_325_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_535)) begin
        if ((icmp_ln114_6_fu_715_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_6_reg_510 <= tmp_21_nbreadreq_fu_200_p3;
        end else if ((icmp_ln114_6_fu_715_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_6_reg_510 <= tmp_20_nbreadreq_fu_208_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_834)) begin
        if ((icmp_ln114_7_fu_765_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_7_reg_569 <= tmp_1_7_nbreadreq_fu_333_p3;
        end else if ((icmp_ln114_7_fu_765_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln114_7_reg_569 <= tmp_1_6_nbreadreq_fu_341_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_905)) begin
        if ((icmp_ln114_4_reg_836 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_tmp_V_load_2_reg_591 <= out_stream_group_4_V_V_dout;
        end else if ((icmp_ln114_4_reg_836 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_tmp_V_load_2_reg_591 <= out_stream_group_12_V_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((1'b1 == ap_condition_123)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_2_3_reg_635 <= out_stream_group_7_V_V_dout;
        end else if ((1'b1 == ap_condition_111)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_2_3_reg_635 <= out_stream_group_15_V_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_2_3_reg_635 <= ap_phi_reg_pp0_iter0_curr_output_0_1_2_3_reg_635;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((phi_ln114_4_reg_500 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_4_2_reg_615 <= ap_phi_reg_pp0_iter0_curr_output_0_1_4_1_reg_579;
        end else if ((phi_ln114_4_reg_500 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_4_2_reg_615 <= ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_curr_output_0_1_4_2_reg_615 <= ap_phi_reg_pp0_iter0_curr_output_0_1_4_2_reg_615;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if (((phi_ln114_6_reg_510 == 1'd1) & (icmp_ln114_6_reg_856 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_tmp_V_load_3_reg_626 <= out_stream_group_6_V_V_dout;
        end else if (((icmp_ln114_6_reg_856 == 1'd0) & (phi_ln114_6_reg_510 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_tmp_V_load_3_reg_626 <= out_stream_group_14_V_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_V_load_3_reg_626 <= ap_phi_reg_pp0_iter0_tmp_V_load_3_reg_626;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_535)) begin
        if (((icmp_ln114_1_fu_679_p2 == 1'd0) & (ap_phi_mux_phi_ln114_phi_fu_430_p4 == 1'd1))) begin
            phi_ln114_1_reg_439 <= tmp_1_1_nbreadreq_fu_152_p3;
        end else if (((ap_phi_mux_phi_ln114_phi_fu_430_p4 == 1'd1) & (icmp_ln114_1_fu_679_p2 == 1'd1))) begin
            phi_ln114_1_reg_439 <= tmp_1_s_nbreadreq_fu_160_p3;
        end else if ((1'b1 == 1'b1)) begin
            phi_ln114_1_reg_439 <= ap_phi_reg_pp0_iter0_phi_ln114_1_reg_439;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_566)) begin
        if (((icmp_ln114_3_fu_735_p2 == 1'd0) & (ap_phi_mux_phi_ln114_2_phi_fu_481_p4 == 1'd1))) begin
            phi_ln114_3_reg_488 <= tmp_1_3_nbreadreq_fu_301_p3;
        end else if (((ap_phi_mux_phi_ln114_2_phi_fu_481_p4 == 1'd1) & (icmp_ln114_3_fu_735_p2 == 1'd1))) begin
            phi_ln114_3_reg_488 <= tmp_1_2_nbreadreq_fu_309_p3;
        end else if ((1'b1 == 1'b1)) begin
            phi_ln114_3_reg_488 <= ap_phi_reg_pp0_iter0_phi_ln114_3_reg_488;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_535)) begin
        if ((icmp_ln114_fu_667_p2 == 1'd0)) begin
            phi_ln114_reg_427 <= tmp_15_nbreadreq_fu_136_p3;
        end else if ((icmp_ln114_fu_667_p2 == 1'd1)) begin
            phi_ln114_reg_427 <= tmp_s_nbreadreq_fu_144_p3;
        end else if ((1'b1 == 1'b1)) begin
            phi_ln114_reg_427 <= ap_phi_reg_pp0_iter0_phi_ln114_reg_427;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        ap_phi_reg_pp0_iter0_curr_output_0_1_4_0_reg_520 <= ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        ap_port_reg_curr_input_dest_V <= curr_input_dest_V;
        ap_port_reg_curr_input_id_V <= curr_input_id_V;
        ap_port_reg_curr_input_keep_V <= curr_input_keep_V;
        ap_port_reg_curr_input_strb_V <= curr_input_strb_V;
        ap_port_reg_curr_input_user_V <= curr_input_user_V;
        ap_port_reg_last_V <= last_V;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_phi_ln114_phi_fu_430_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        icmp_ln114_1_reg_818 <= icmp_ln114_1_fu_679_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        icmp_ln114_2_reg_822 <= icmp_ln114_2_fu_691_p2;
        icmp_ln114_4_reg_836 <= icmp_ln114_4_fu_703_p2;
        icmp_ln114_6_reg_856 <= icmp_ln114_6_fu_715_p2;
        icmp_ln114_reg_814 <= icmp_ln114_fu_667_p2;
        or_ln228_reg_850[2] <= or_ln228_fu_709_p2[2];
        shl_ln1_reg_808[3] <= shl_ln1_fu_659_p3[3];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_phi_ln114_2_phi_fu_481_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        icmp_ln114_3_reg_895 <= icmp_ln114_3_fu_735_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_phi_ln114_4_phi_fu_503_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        icmp_ln114_5_reg_899 <= icmp_ln114_5_fu_746_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_phi_ln114_6_phi_fu_513_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        icmp_ln114_7_reg_913 <= icmp_ln114_7_fu_765_p2;
        icmp_ln251_reg_927 <= icmp_ln251_fu_771_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        phi_ln114_2_reg_478 <= ap_phi_reg_pp0_iter0_phi_ln114_2_reg_478;
        phi_ln114_4_reg_500 <= ap_phi_reg_pp0_iter0_phi_ln114_4_reg_500;
        phi_ln114_6_reg_510 <= ap_phi_reg_pp0_iter0_phi_ln114_6_reg_510;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce))) begin
        phi_ln114_5_reg_559 <= ap_phi_reg_pp0_iter0_phi_ln114_5_reg_559;
        phi_ln114_7_reg_569 <= ap_phi_reg_pp0_iter0_phi_ln114_7_reg_569;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        tmp_dest_V_reg_870 <= ap_port_reg_curr_input_dest_V;
        tmp_id_V_reg_875 <= ap_port_reg_curr_input_id_V;
        tmp_keep_V_reg_890 <= ap_port_reg_curr_input_keep_V;
        tmp_strb_V_reg_885 <= ap_port_reg_curr_input_strb_V;
        tmp_user_V_reg_880 <= ap_port_reg_curr_input_user_V;
    end
end

always @ (posedge ap_clk) begin
    if (((phi_ln114_6_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_last_V_reg_962 <= tmp_last_V_fu_794_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)) | ((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_874)) begin
        if ((icmp_ln114_1_reg_818 == 1'd1)) begin
            ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6 = out_stream_group_1_V_V_dout;
        end else if ((icmp_ln114_1_reg_818 == 1'd0)) begin
            ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6 = out_stream_group_9_V_V_dout;
        end else begin
            ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_0_reg_462;
        end
    end else begin
        ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_0_reg_462;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_295)) begin
        if (((phi_ln114_3_reg_488 == 1'd1) & (icmp_ln114_3_reg_895 == 1'd1))) begin
            ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6 = out_stream_group_3_V_V_dout;
        end else if (((icmp_ln114_3_reg_895 == 1'd0) & (phi_ln114_3_reg_488 == 1'd1))) begin
            ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6 = out_stream_group_11_V_V_dout;
        end else if ((phi_ln114_3_reg_488 == 1'd0)) begin
            ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_4_0_reg_520;
        end else begin
            ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_1_reg_544;
        end
    end else begin
        ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_1_reg_544;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_297)) begin
        if (((phi_ln114_5_reg_559 == 1'd1) & (icmp_ln114_5_reg_899 == 1'd1))) begin
            ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6 = out_stream_group_5_V_V_dout;
        end else if (((icmp_ln114_5_reg_899 == 1'd0) & (phi_ln114_5_reg_559 == 1'd1))) begin
            ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6 = out_stream_group_13_V_V_dout;
        end else if ((phi_ln114_5_reg_559 == 1'd0)) begin
            ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_4_1_reg_579;
        end else begin
            ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_2_reg_600;
        end
    end else begin
        ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6 = ap_phi_reg_pp0_iter0_curr_output_0_1_2_2_reg_600;
    end
end

always @ (*) begin
    if (((phi_ln114_7_reg_569 == 1'd0) & (phi_ln114_6_reg_510 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_curr_output_0_1_2_3_phi_fu_638_p6 = ap_phi_reg_pp0_iter1_curr_output_0_1_4_2_reg_615;
    end else begin
        ap_phi_mux_curr_output_0_1_2_3_phi_fu_638_p6 = ap_phi_reg_pp0_iter1_curr_output_0_1_2_3_reg_635;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_28)) begin
        if ((icmp_ln114_fu_667_p2 == 1'd0)) begin
            ap_phi_mux_phi_ln114_phi_fu_430_p4 = tmp_15_nbreadreq_fu_136_p3;
        end else if ((icmp_ln114_fu_667_p2 == 1'd1)) begin
            ap_phi_mux_phi_ln114_phi_fu_430_p4 = tmp_s_nbreadreq_fu_144_p3;
        end else begin
            ap_phi_mux_phi_ln114_phi_fu_430_p4 = ap_phi_reg_pp0_iter0_phi_ln114_reg_427;
        end
    end else begin
        ap_phi_mux_phi_ln114_phi_fu_430_p4 = ap_phi_reg_pp0_iter0_phi_ln114_reg_427;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_295)) begin
        if ((icmp_ln114_2_reg_822 == 1'd1)) begin
            ap_phi_mux_tmp_V_load_1_phi_fu_536_p4 = out_stream_group_2_V_V_dout;
        end else if ((icmp_ln114_2_reg_822 == 1'd0)) begin
            ap_phi_mux_tmp_V_load_1_phi_fu_536_p4 = out_stream_group_10_V_V_dout;
        end else begin
            ap_phi_mux_tmp_V_load_1_phi_fu_536_p4 = ap_phi_reg_pp0_iter0_tmp_V_load_1_reg_533;
        end
    end else begin
        ap_phi_mux_tmp_V_load_1_phi_fu_536_p4 = ap_phi_reg_pp0_iter0_tmp_V_load_1_reg_533;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_294)) begin
        if ((icmp_ln114_reg_814 == 1'd1)) begin
            ap_phi_mux_tmp_V_load_phi_fu_454_p4 = out_stream_group_0_V_V_dout;
        end else if ((icmp_ln114_reg_814 == 1'd0)) begin
            ap_phi_mux_tmp_V_load_phi_fu_454_p4 = out_stream_group_8_V_V_dout;
        end else begin
            ap_phi_mux_tmp_V_load_phi_fu_454_p4 = ap_phi_reg_pp0_iter0_tmp_V_load_reg_451;
        end
    end else begin
        ap_phi_mux_tmp_V_load_phi_fu_454_p4 = ap_phi_reg_pp0_iter0_tmp_V_load_reg_451;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_ce)) begin
        if ((1'b1 == ap_condition_928)) begin
            outStream_TDATA = tmp_data_3_fu_799_p3;
        end else if ((1'b1 == ap_condition_923)) begin
            outStream_TDATA = tmp_data_2_fu_785_p3;
        end else if ((1'b1 == ap_condition_920)) begin
            outStream_TDATA = tmp_data_1_fu_776_p3;
        end else if ((1'b1 == ap_condition_916)) begin
            outStream_TDATA = tmp_data_fu_721_p3;
        end else begin
            outStream_TDATA = 'bx;
        end
    end else begin
        outStream_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((phi_ln114_4_reg_500 == 1'd1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((phi_ln114_6_reg_510 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        outStream_TDATA_blk_n = outStream_TREADY;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TDEST = tmp_dest_V_reg_870;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        outStream_TDEST = ap_port_reg_curr_input_dest_V;
    end else begin
        outStream_TDEST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TID = tmp_id_V_reg_875;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        outStream_TID = ap_port_reg_curr_input_id_V;
    end else begin
        outStream_TID = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TKEEP = tmp_keep_V_reg_890;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        outStream_TKEEP = ap_port_reg_curr_input_keep_V;
    end else begin
        outStream_TKEEP = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce))) begin
        outStream_TLAST = tmp_last_V_reg_962;
    end else if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)))) begin
        outStream_TLAST = 1'd0;
    end else begin
        outStream_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TSTRB = tmp_strb_V_reg_885;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        outStream_TSTRB = ap_port_reg_curr_input_strb_V;
    end else begin
        outStream_TSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TUSER = tmp_user_V_reg_880;
    end else if (((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        outStream_TUSER = ap_port_reg_curr_input_user_V;
    end else begin
        outStream_TUSER = 'bx;
    end
end

always @ (*) begin
    if ((((phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001)) | ((phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce)) | ((phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce)) | ((phi_ln114_6_reg_510 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce)))) begin
        outStream_TVALID = 1'b1;
    end else begin
        outStream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln114_reg_427 == 1'd1) & (icmp_ln114_reg_814 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_stream_group_0_V_V_blk_n = out_stream_group_0_V_V_empty_n;
    end else begin
        out_stream_group_0_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce) & (ap_predicate_op54_read_state2 == 1'b1))) begin
        out_stream_group_0_V_V_read = 1'b1;
    end else begin
        out_stream_group_0_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_2_reg_822 == 1'd0) & (phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_10_V_V_blk_n = out_stream_group_10_V_V_empty_n;
    end else begin
        out_stream_group_10_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op100_read_state3 == 1'b1))) begin
        out_stream_group_10_V_V_read = 1'b1;
    end else begin
        out_stream_group_10_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_3_reg_895 == 1'd0) & (phi_ln114_3_reg_488 == 1'd1) & (phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_11_V_V_blk_n = out_stream_group_11_V_V_empty_n;
    end else begin
        out_stream_group_11_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op106_read_state3 == 1'b1))) begin
        out_stream_group_11_V_V_read = 1'b1;
    end else begin
        out_stream_group_11_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_4_reg_836 == 1'd0) & (phi_ln114_4_reg_500 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_12_V_V_blk_n = out_stream_group_12_V_V_empty_n;
    end else begin
        out_stream_group_12_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op114_read_state3 == 1'b1))) begin
        out_stream_group_12_V_V_read = 1'b1;
    end else begin
        out_stream_group_12_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op129_read_state4 == 1'b1))) begin
        out_stream_group_13_V_V_blk_n = out_stream_group_13_V_V_empty_n;
    end else begin
        out_stream_group_13_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op129_read_state4 == 1'b1))) begin
        out_stream_group_13_V_V_read = 1'b1;
    end else begin
        out_stream_group_13_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op137_read_state4 == 1'b1))) begin
        out_stream_group_14_V_V_blk_n = out_stream_group_14_V_V_empty_n;
    end else begin
        out_stream_group_14_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op137_read_state4 == 1'b1))) begin
        out_stream_group_14_V_V_read = 1'b1;
    end else begin
        out_stream_group_14_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op141_read_state4 == 1'b1))) begin
        out_stream_group_15_V_V_blk_n = out_stream_group_15_V_V_empty_n;
    end else begin
        out_stream_group_15_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op141_read_state4 == 1'b1))) begin
        out_stream_group_15_V_V_read = 1'b1;
    end else begin
        out_stream_group_15_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln114_1_reg_439 == 1'd1) & (icmp_ln114_1_reg_818 == 1'd1) & (phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_stream_group_1_V_V_blk_n = out_stream_group_1_V_V_empty_n;
    end else begin
        out_stream_group_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce) & (ap_predicate_op59_read_state2 == 1'b1))) begin
        out_stream_group_1_V_V_read = 1'b1;
    end else begin
        out_stream_group_1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln114_2_reg_478 == 1'd1) & (icmp_ln114_2_reg_822 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_2_V_V_blk_n = out_stream_group_2_V_V_empty_n;
    end else begin
        out_stream_group_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op102_read_state3 == 1'b1))) begin
        out_stream_group_2_V_V_read = 1'b1;
    end else begin
        out_stream_group_2_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((phi_ln114_3_reg_488 == 1'd1) & (icmp_ln114_3_reg_895 == 1'd1) & (phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_3_V_V_blk_n = out_stream_group_3_V_V_empty_n;
    end else begin
        out_stream_group_3_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op108_read_state3 == 1'b1))) begin
        out_stream_group_3_V_V_read = 1'b1;
    end else begin
        out_stream_group_3_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_4_reg_836 == 1'd1) & (phi_ln114_4_reg_500 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_stream_group_4_V_V_blk_n = out_stream_group_4_V_V_empty_n;
    end else begin
        out_stream_group_4_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (ap_predicate_op116_read_state3 == 1'b1))) begin
        out_stream_group_4_V_V_read = 1'b1;
    end else begin
        out_stream_group_4_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op131_read_state4 == 1'b1))) begin
        out_stream_group_5_V_V_blk_n = out_stream_group_5_V_V_empty_n;
    end else begin
        out_stream_group_5_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op131_read_state4 == 1'b1))) begin
        out_stream_group_5_V_V_read = 1'b1;
    end else begin
        out_stream_group_5_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op139_read_state4 == 1'b1))) begin
        out_stream_group_6_V_V_blk_n = out_stream_group_6_V_V_empty_n;
    end else begin
        out_stream_group_6_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op139_read_state4 == 1'b1))) begin
        out_stream_group_6_V_V_read = 1'b1;
    end else begin
        out_stream_group_6_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op143_read_state4 == 1'b1))) begin
        out_stream_group_7_V_V_blk_n = out_stream_group_7_V_V_empty_n;
    end else begin
        out_stream_group_7_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op143_read_state4 == 1'b1))) begin
        out_stream_group_7_V_V_read = 1'b1;
    end else begin
        out_stream_group_7_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_reg_814 == 1'd0) & (phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_stream_group_8_V_V_blk_n = out_stream_group_8_V_V_empty_n;
    end else begin
        out_stream_group_8_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce) & (ap_predicate_op52_read_state2 == 1'b1))) begin
        out_stream_group_8_V_V_read = 1'b1;
    end else begin
        out_stream_group_8_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln114_1_reg_818 == 1'd0) & (phi_ln114_1_reg_439 == 1'd1) & (phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_stream_group_9_V_V_blk_n = out_stream_group_9_V_V_empty_n;
    end else begin
        out_stream_group_9_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce) & (ap_predicate_op57_read_state2 == 1'b1))) begin
        out_stream_group_9_V_V_read = 1'b1;
    end else begin
        out_stream_group_9_V_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_io)) | ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((out_stream_group_1_V_V_empty_n == 1'b0) & (ap_predicate_op59_read_state2 == 1'b1)) | ((out_stream_group_9_V_V_empty_n == 1'b0) & (ap_predicate_op57_read_state2 == 1'b1)) | ((out_stream_group_0_V_V_empty_n == 1'b0) & (ap_predicate_op54_read_state2 == 1'b1)) | ((out_stream_group_8_V_V_empty_n == 1'b0) & (ap_predicate_op52_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((out_stream_group_1_V_V_empty_n == 1'b0) & (ap_predicate_op59_read_state2 == 1'b1)) | ((out_stream_group_9_V_V_empty_n == 1'b0) & (ap_predicate_op57_read_state2 == 1'b1)) | ((out_stream_group_0_V_V_empty_n == 1'b0) & (ap_predicate_op54_read_state2 == 1'b1)) | ((out_stream_group_8_V_V_empty_n == 1'b0) & (ap_predicate_op52_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((out_stream_group_1_V_V_empty_n == 1'b0) & (ap_predicate_op59_read_state2 == 1'b1)) | ((out_stream_group_9_V_V_empty_n == 1'b0) & (ap_predicate_op57_read_state2 == 1'b1)) | ((out_stream_group_0_V_V_empty_n == 1'b0) & (ap_predicate_op54_read_state2 == 1'b1)) | ((out_stream_group_8_V_V_empty_n == 1'b0) & (ap_predicate_op52_read_state2 == 1'b1)))));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((out_stream_group_4_V_V_empty_n == 1'b0) & (ap_predicate_op116_read_state3 == 1'b1)) | ((out_stream_group_12_V_V_empty_n == 1'b0) & (ap_predicate_op114_read_state3 == 1'b1)) | ((out_stream_group_3_V_V_empty_n == 1'b0) & (ap_predicate_op108_read_state3 == 1'b1)) | ((out_stream_group_11_V_V_empty_n == 1'b0) & (ap_predicate_op106_read_state3 == 1'b1)) | ((out_stream_group_2_V_V_empty_n == 1'b0) & (ap_predicate_op102_read_state3 == 1'b1)) | ((out_stream_group_10_V_V_empty_n == 1'b0) & (ap_predicate_op100_read_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((out_stream_group_4_V_V_empty_n == 1'b0) & (ap_predicate_op116_read_state3 == 1'b1)) | ((out_stream_group_12_V_V_empty_n == 1'b0) & (ap_predicate_op114_read_state3 == 1'b1)) | ((out_stream_group_3_V_V_empty_n == 1'b0) & (ap_predicate_op108_read_state3 == 1'b1)) | ((out_stream_group_11_V_V_empty_n == 1'b0) & (ap_predicate_op106_read_state3 == 1'b1)) | ((out_stream_group_2_V_V_empty_n == 1'b0) & (ap_predicate_op102_read_state3 == 1'b1)) | ((out_stream_group_10_V_V_empty_n == 1'b0) & (ap_predicate_op100_read_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((out_stream_group_4_V_V_empty_n == 1'b0) & (ap_predicate_op116_read_state3 == 1'b1)) | ((out_stream_group_12_V_V_empty_n == 1'b0) & (ap_predicate_op114_read_state3 == 1'b1)) | ((out_stream_group_3_V_V_empty_n == 1'b0) & (ap_predicate_op108_read_state3 == 1'b1)) | ((out_stream_group_11_V_V_empty_n == 1'b0) & (ap_predicate_op106_read_state3 == 1'b1)) | ((out_stream_group_2_V_V_empty_n == 1'b0) & (ap_predicate_op102_read_state3 == 1'b1)) | ((out_stream_group_10_V_V_empty_n == 1'b0) & (ap_predicate_op100_read_state3 == 1'b1)))));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((out_stream_group_6_V_V_empty_n == 1'b0) & (ap_predicate_op139_read_state4 == 1'b1)) | ((out_stream_group_14_V_V_empty_n == 1'b0) & (ap_predicate_op137_read_state4 == 1'b1)) | ((out_stream_group_5_V_V_empty_n == 1'b0) & (ap_predicate_op131_read_state4 == 1'b1)) | ((out_stream_group_13_V_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1)) | ((out_stream_group_7_V_V_empty_n == 1'b0) & (ap_predicate_op143_read_state4 == 1'b1)) | ((out_stream_group_15_V_V_empty_n == 1'b0) & (ap_predicate_op141_read_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((out_stream_group_6_V_V_empty_n == 1'b0) & (ap_predicate_op139_read_state4 == 1'b1)) | ((out_stream_group_14_V_V_empty_n == 1'b0) & (ap_predicate_op137_read_state4 == 1'b1)) | ((out_stream_group_5_V_V_empty_n == 1'b0) & (ap_predicate_op131_read_state4 == 1'b1)) | ((out_stream_group_13_V_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1)) | ((out_stream_group_7_V_V_empty_n == 1'b0) & (ap_predicate_op143_read_state4 == 1'b1)) | ((out_stream_group_15_V_V_empty_n == 1'b0) & (ap_predicate_op141_read_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'b0 == ap_ce) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((out_stream_group_6_V_V_empty_n == 1'b0) & (ap_predicate_op139_read_state4 == 1'b1)) | ((out_stream_group_14_V_V_empty_n == 1'b0) & (ap_predicate_op137_read_state4 == 1'b1)) | ((out_stream_group_5_V_V_empty_n == 1'b0) & (ap_predicate_op131_read_state4 == 1'b1)) | ((out_stream_group_13_V_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1)) | ((out_stream_group_7_V_V_empty_n == 1'b0) & (ap_predicate_op143_read_state4 == 1'b1)) | ((out_stream_group_15_V_V_empty_n == 1'b0) & (ap_predicate_op141_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state2_io = ((phi_ln114_reg_427 == 1'd1) & (outStream_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((out_stream_group_1_V_V_empty_n == 1'b0) & (ap_predicate_op59_read_state2 == 1'b1)) | ((out_stream_group_9_V_V_empty_n == 1'b0) & (ap_predicate_op57_read_state2 == 1'b1)) | ((out_stream_group_0_V_V_empty_n == 1'b0) & (ap_predicate_op54_read_state2 == 1'b1)) | ((out_stream_group_8_V_V_empty_n == 1'b0) & (ap_predicate_op52_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = ((phi_ln114_2_reg_478 == 1'd1) & (outStream_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (((out_stream_group_4_V_V_empty_n == 1'b0) & (ap_predicate_op116_read_state3 == 1'b1)) | ((out_stream_group_12_V_V_empty_n == 1'b0) & (ap_predicate_op114_read_state3 == 1'b1)) | ((out_stream_group_3_V_V_empty_n == 1'b0) & (ap_predicate_op108_read_state3 == 1'b1)) | ((out_stream_group_11_V_V_empty_n == 1'b0) & (ap_predicate_op106_read_state3 == 1'b1)) | ((out_stream_group_2_V_V_empty_n == 1'b0) & (ap_predicate_op102_read_state3 == 1'b1)) | ((out_stream_group_10_V_V_empty_n == 1'b0) & (ap_predicate_op100_read_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_io = ((phi_ln114_4_reg_500 == 1'd1) & (outStream_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = (((out_stream_group_6_V_V_empty_n == 1'b0) & (ap_predicate_op139_read_state4 == 1'b1)) | ((out_stream_group_14_V_V_empty_n == 1'b0) & (ap_predicate_op137_read_state4 == 1'b1)) | ((out_stream_group_5_V_V_empty_n == 1'b0) & (ap_predicate_op131_read_state4 == 1'b1)) | ((out_stream_group_13_V_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1)) | ((out_stream_group_7_V_V_empty_n == 1'b0) & (ap_predicate_op143_read_state4 == 1'b1)) | ((out_stream_group_15_V_V_empty_n == 1'b0) & (ap_predicate_op141_read_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_io = ((phi_ln114_6_reg_510 == 1'd1) & (outStream_TREADY == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_111 = ((icmp_ln114_7_reg_913 == 1'd0) & (phi_ln114_6_reg_510 == 1'd1) & (phi_ln114_7_reg_569 == 1'd1));
end

always @ (*) begin
    ap_condition_123 = ((phi_ln114_6_reg_510 == 1'd1) & (phi_ln114_7_reg_569 == 1'd1) & (icmp_ln114_7_reg_913 == 1'd1));
end

always @ (*) begin
    ap_condition_144 = ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage3_11001));
end

always @ (*) begin
    ap_condition_28 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_294 = ((phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_295 = ((phi_ln114_2_reg_478 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_297 = ((phi_ln114_4_reg_500 == 1'd1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_535 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_566 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_601 = ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_830 = ((ap_phi_mux_phi_ln114_4_phi_fu_503_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_834 = ((ap_phi_mux_phi_ln114_6_phi_fu_513_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_874 = ((phi_ln114_1_reg_439 == 1'd1) & (phi_ln114_reg_427 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_905 = ((phi_ln114_4_reg_500 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce));
end

always @ (*) begin
    ap_condition_916 = ((1'b0 == ap_block_pp0_stage1_01001) & (phi_ln114_reg_427 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_920 = ((1'b0 == ap_block_pp0_stage2_01001) & (phi_ln114_2_reg_478 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_923 = ((1'b0 == ap_block_pp0_stage3_01001) & (phi_ln114_4_reg_500 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_928 = ((1'b0 == ap_block_pp0_stage0_01001) & (phi_ln114_6_reg_510 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_mux_phi_ln114_2_phi_fu_481_p4 = ap_phi_reg_pp0_iter0_phi_ln114_2_reg_478;

assign ap_phi_mux_phi_ln114_4_phi_fu_503_p4 = ap_phi_reg_pp0_iter0_phi_ln114_4_reg_500;

assign ap_phi_mux_phi_ln114_6_phi_fu_513_p4 = ap_phi_reg_pp0_iter0_phi_ln114_6_reg_510;

assign ap_phi_reg_pp0_iter0_curr_output_0_1_2_0_reg_462 = 'bx;

assign ap_phi_reg_pp0_iter0_curr_output_0_1_2_1_reg_544 = 'bx;

assign ap_phi_reg_pp0_iter0_curr_output_0_1_2_2_reg_600 = 'bx;

assign ap_phi_reg_pp0_iter0_curr_output_0_1_2_3_reg_635 = 'bx;

assign ap_phi_reg_pp0_iter0_curr_output_0_1_4_2_reg_615 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln114_1_reg_439 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln114_3_reg_488 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln114_reg_427 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_V_load_1_reg_533 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_V_load_3_reg_626 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_V_load_reg_451 = 'bx;

always @ (*) begin
    ap_predicate_op100_read_state3 = ((icmp_ln114_2_reg_822 == 1'd0) & (phi_ln114_2_reg_478 == 1'd1));
end

always @ (*) begin
    ap_predicate_op102_read_state3 = ((phi_ln114_2_reg_478 == 1'd1) & (icmp_ln114_2_reg_822 == 1'd1));
end

always @ (*) begin
    ap_predicate_op106_read_state3 = ((icmp_ln114_3_reg_895 == 1'd0) & (phi_ln114_3_reg_488 == 1'd1) & (phi_ln114_2_reg_478 == 1'd1));
end

always @ (*) begin
    ap_predicate_op108_read_state3 = ((phi_ln114_3_reg_488 == 1'd1) & (icmp_ln114_3_reg_895 == 1'd1) & (phi_ln114_2_reg_478 == 1'd1));
end

always @ (*) begin
    ap_predicate_op114_read_state3 = ((icmp_ln114_4_reg_836 == 1'd0) & (phi_ln114_4_reg_500 == 1'd1));
end

always @ (*) begin
    ap_predicate_op116_read_state3 = ((icmp_ln114_4_reg_836 == 1'd1) & (phi_ln114_4_reg_500 == 1'd1));
end

always @ (*) begin
    ap_predicate_op129_read_state4 = ((icmp_ln114_5_reg_899 == 1'd0) & (phi_ln114_5_reg_559 == 1'd1) & (phi_ln114_4_reg_500 == 1'd1));
end

always @ (*) begin
    ap_predicate_op131_read_state4 = ((phi_ln114_5_reg_559 == 1'd1) & (icmp_ln114_5_reg_899 == 1'd1) & (phi_ln114_4_reg_500 == 1'd1));
end

always @ (*) begin
    ap_predicate_op137_read_state4 = ((icmp_ln114_6_reg_856 == 1'd0) & (phi_ln114_6_reg_510 == 1'd1));
end

always @ (*) begin
    ap_predicate_op139_read_state4 = ((phi_ln114_6_reg_510 == 1'd1) & (icmp_ln114_6_reg_856 == 1'd1));
end

always @ (*) begin
    ap_predicate_op141_read_state4 = ((icmp_ln114_7_reg_913 == 1'd0) & (phi_ln114_6_reg_510 == 1'd1) & (phi_ln114_7_reg_569 == 1'd1));
end

always @ (*) begin
    ap_predicate_op143_read_state4 = ((phi_ln114_6_reg_510 == 1'd1) & (phi_ln114_7_reg_569 == 1'd1) & (icmp_ln114_7_reg_913 == 1'd1));
end

always @ (*) begin
    ap_predicate_op52_read_state2 = ((icmp_ln114_reg_814 == 1'd0) & (phi_ln114_reg_427 == 1'd1));
end

always @ (*) begin
    ap_predicate_op54_read_state2 = ((phi_ln114_reg_427 == 1'd1) & (icmp_ln114_reg_814 == 1'd1));
end

always @ (*) begin
    ap_predicate_op57_read_state2 = ((icmp_ln114_1_reg_818 == 1'd0) & (phi_ln114_1_reg_439 == 1'd1) & (phi_ln114_reg_427 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_read_state2 = ((phi_ln114_1_reg_439 == 1'd1) & (icmp_ln114_1_reg_818 == 1'd1) & (phi_ln114_reg_427 == 1'd1));
end

assign icmp_ln114_1_fu_679_p2 = ((or_ln114_fu_673_p2 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln114_2_fu_691_p2 = ((or_ln114_1_fu_685_p2 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln114_3_fu_735_p2 = ((or_ln114_2_fu_730_p2 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln114_4_fu_703_p2 = ((or_ln114_3_fu_697_p2 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln114_5_fu_746_p2 = ((or_ln114_4_fu_741_p2 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln114_6_fu_715_p2 = ((or_ln228_fu_709_p2 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln114_7_fu_765_p2 = ((or_ln114_5_fu_759_p2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_667_p2 = ((shl_ln1_fu_659_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln251_fu_771_p2 = ((or_ln228_reg_850 == 3'd7) ? 1'b1 : 1'b0);

assign or_ln114_1_fu_685_p2 = (shl_ln1_fu_659_p3 | 4'd2);

assign or_ln114_2_fu_730_p2 = (shl_ln1_reg_808 | 4'd3);

assign or_ln114_3_fu_697_p2 = (shl_ln1_fu_659_p3 | 4'd4);

assign or_ln114_4_fu_741_p2 = (shl_ln1_reg_808 | 4'd5);

assign or_ln114_5_fu_759_p2 = (shl_ln2_fu_752_p3 | 4'd1);

assign or_ln114_fu_673_p2 = (shl_ln1_fu_659_p3 | 4'd1);

assign or_ln228_fu_709_p2 = (shl_ln_fu_651_p3 | 3'd3);

assign shl_ln1_fu_659_p3 = {{trunc_ln228_fu_647_p1}, {3'd0}};

assign shl_ln2_fu_752_p3 = {{or_ln228_reg_850}, {1'd0}};

assign shl_ln_fu_651_p3 = {{trunc_ln228_fu_647_p1}, {2'd0}};

assign tmp_15_nbreadreq_fu_136_p3 = out_stream_group_8_V_V_empty_n;

assign tmp_16_nbreadreq_fu_176_p3 = out_stream_group_2_V_V_empty_n;

assign tmp_17_nbreadreq_fu_168_p3 = out_stream_group_10_V_V_empty_n;

assign tmp_18_nbreadreq_fu_192_p3 = out_stream_group_4_V_V_empty_n;

assign tmp_19_nbreadreq_fu_184_p3 = out_stream_group_12_V_V_empty_n;

assign tmp_1_1_nbreadreq_fu_152_p3 = out_stream_group_9_V_V_empty_n;

assign tmp_1_2_nbreadreq_fu_309_p3 = out_stream_group_3_V_V_empty_n;

assign tmp_1_3_nbreadreq_fu_301_p3 = out_stream_group_11_V_V_empty_n;

assign tmp_1_4_nbreadreq_fu_325_p3 = out_stream_group_5_V_V_empty_n;

assign tmp_1_5_nbreadreq_fu_317_p3 = out_stream_group_13_V_V_empty_n;

assign tmp_1_6_nbreadreq_fu_341_p3 = out_stream_group_7_V_V_empty_n;

assign tmp_1_7_nbreadreq_fu_333_p3 = out_stream_group_15_V_V_empty_n;

assign tmp_1_s_nbreadreq_fu_160_p3 = out_stream_group_1_V_V_empty_n;

assign tmp_20_nbreadreq_fu_208_p3 = out_stream_group_6_V_V_empty_n;

assign tmp_21_nbreadreq_fu_200_p3 = out_stream_group_14_V_V_empty_n;

assign tmp_data_1_fu_776_p3 = {{ap_phi_mux_curr_output_0_1_2_1_phi_fu_547_p6}, {ap_phi_mux_tmp_V_load_1_phi_fu_536_p4}};

assign tmp_data_2_fu_785_p3 = {{ap_phi_mux_curr_output_0_1_2_2_phi_fu_603_p6}, {ap_phi_reg_pp0_iter0_tmp_V_load_2_reg_591}};

assign tmp_data_3_fu_799_p3 = {{ap_phi_mux_curr_output_0_1_2_3_phi_fu_638_p6}, {ap_phi_reg_pp0_iter1_tmp_V_load_3_reg_626}};

assign tmp_data_fu_721_p3 = {{ap_phi_mux_curr_output_0_1_2_0_phi_fu_466_p6}, {ap_phi_mux_tmp_V_load_phi_fu_454_p4}};

assign tmp_last_V_fu_794_p2 = (icmp_ln251_reg_927 & ap_port_reg_last_V);

assign tmp_s_nbreadreq_fu_144_p3 = out_stream_group_0_V_V_empty_n;

assign trunc_ln228_fu_647_p1 = input_ch_idx[0:0];

always @ (posedge ap_clk) begin
    shl_ln1_reg_808[2:0] <= 3'b000;
    or_ln228_reg_850[1:0] <= 2'b11;
end

endmodule //out_stream_merge
