#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("inStream_TDATA", 64, hls_in, 0, "axis", "in_data", 1),
	Port_Property("inStream_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("inStream_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("inStream_TKEEP", 8, hls_in, 1, "axis", "in_data", 1),
	Port_Property("inStream_TSTRB", 8, hls_in, 2, "axis", "in_data", 1),
	Port_Property("inStream_TUSER", 2, hls_in, 3, "axis", "in_data", 1),
	Port_Property("inStream_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("inStream_TID", 5, hls_in, 5, "axis", "in_data", 1),
	Port_Property("inStream_TDEST", 6, hls_in, 6, "axis", "in_data", 1),
	Port_Property("outStream_TDATA", 64, hls_out, 7, "axis", "out_data", 1),
	Port_Property("outStream_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("outStream_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("outStream_TKEEP", 8, hls_out, 8, "axis", "out_data", 1),
	Port_Property("outStream_TSTRB", 8, hls_out, 9, "axis", "out_data", 1),
	Port_Property("outStream_TUSER", 2, hls_out, 10, "axis", "out_data", 1),
	Port_Property("outStream_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("outStream_TID", 5, hls_out, 12, "axis", "out_data", 1),
	Port_Property("outStream_TDEST", 6, hls_out, 13, "axis", "out_data", 1),
	Port_Property("s_axi_AXILiteS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_AXILiteS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "yolo_conv_top";
