# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/yolo_sys/yolo_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys || ORIG_REF_NAME==yolo_sys} -quiet] -quiet

# IP: bd/yolo_sys/ip/yolo_sys_processing_system7_0_0/yolo_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys_processing_system7_0_0 || ORIG_REF_NAME==yolo_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/yolo_sys/ip/yolo_sys_axi_gpio_0_0/yolo_sys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys_axi_gpio_0_0 || ORIG_REF_NAME==yolo_sys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/yolo_sys/ip/yolo_sys_ps7_0_axi_periph_0/yolo_sys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==yolo_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/yolo_sys/ip/yolo_sys_rst_ps7_0_100M_0/yolo_sys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==yolo_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/yolo_sys/ip/yolo_sys_auto_pc_0/yolo_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yolo_sys_auto_pc_0 || ORIG_REF_NAME==yolo_sys_auto_pc_0} -quiet] -quiet

# XDC: bd/yolo_sys/yolo_sys_ooc.xdc
