// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _exp_16_8_s_HH_
#define _exp_16_8_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "exp_16_8_s_f_x_lsb_table_V.h"
#include "exp_16_8_s_exp_x_msb_2_m_1_tabl.h"
#include "exp_16_8_s_exp_x_msb_1_table_V.h"

namespace ap_rtl {

struct exp_16_8_s : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_ce;
    sc_in< sc_lv<16> > x_V;
    sc_out< sc_lv<16> > ap_return;


    // Module declarations
    exp_16_8_s(sc_module_name name);
    SC_HAS_PROCESS(exp_16_8_s);

    ~exp_16_8_s();

    sc_trace_file* mVcdFile;

    exp_16_8_s_f_x_lsb_table_V* f_x_lsb_table_V_U;
    exp_16_8_s_exp_x_msb_2_m_1_tabl* exp_x_msb_2_m_1_tabl_U;
    exp_16_8_s_exp_x_msb_1_table_V* exp_x_msb_1_table_V_U;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<5> > f_x_lsb_table_V_address0;
    sc_signal< sc_logic > f_x_lsb_table_V_ce0;
    sc_signal< sc_lv<11> > f_x_lsb_table_V_q0;
    sc_signal< sc_lv<5> > exp_x_msb_2_m_1_tabl_address0;
    sc_signal< sc_logic > exp_x_msb_2_m_1_tabl_ce0;
    sc_signal< sc_lv<25> > exp_x_msb_2_m_1_tabl_q0;
    sc_signal< sc_lv<5> > exp_x_msb_1_table_V_address0;
    sc_signal< sc_logic > exp_x_msb_1_table_V_ce0;
    sc_signal< sc_lv<25> > exp_x_msb_1_table_V_q0;
    sc_signal< sc_lv<1> > tmp_fu_183_p3;
    sc_signal< sc_lv<1> > tmp_reg_591;
    sc_signal< sc_lv<1> > tmp_reg_591_pp0_iter1_reg;
    sc_signal< sc_lv<1> > tmp_reg_591_pp0_iter2_reg;
    sc_signal< sc_lv<1> > tmp_reg_591_pp0_iter3_reg;
    sc_signal< sc_lv<1> > tmp_reg_591_pp0_iter4_reg;
    sc_signal< sc_lv<4> > p_Result_s_19_reg_597;
    sc_signal< sc_lv<4> > p_Result_s_19_reg_597_pp0_iter1_reg;
    sc_signal< sc_lv<2> > trunc_ln612_1_fu_341_p1;
    sc_signal< sc_lv<2> > trunc_ln612_1_reg_602;
    sc_signal< sc_lv<2> > trunc_ln612_1_reg_602_pp0_iter1_reg;
    sc_signal< sc_lv<2> > trunc_ln612_1_reg_602_pp0_iter2_reg;
    sc_signal< sc_lv<1> > or_ln194_7_fu_405_p2;
    sc_signal< sc_lv<1> > or_ln194_7_reg_618;
    sc_signal< sc_lv<1> > or_ln194_7_reg_618_pp0_iter1_reg;
    sc_signal< sc_lv<1> > or_ln194_7_reg_618_pp0_iter2_reg;
    sc_signal< sc_lv<1> > or_ln194_7_reg_618_pp0_iter3_reg;
    sc_signal< sc_lv<1> > or_ln194_7_reg_618_pp0_iter4_reg;
    sc_signal< sc_lv<11> > f_x_lsb_V_reg_623;
    sc_signal< sc_lv<11> > f_x_lsb_V_reg_623_pp0_iter2_reg;
    sc_signal< sc_lv<25> > exp_x_msb_2_m_1_V_reg_629;
    sc_signal< sc_lv<25> > exp_x_msb_2_m_1_V_reg_629_pp0_iter2_reg;
    sc_signal< sc_lv<19> > f_x_msb_2_lsb_s_V_reg_635;
    sc_signal< sc_lv<25> > exp_x_msb_2_lsb_m_1_s_fu_480_p2;
    sc_signal< sc_lv<25> > exp_x_msb_2_lsb_m_1_s_reg_645;
    sc_signal< sc_lv<25> > exp_x_msb_1_V_reg_650;
    sc_signal< sc_lv<25> > exp_x_msb_1_V_reg_650_pp0_iter4_reg;
    sc_signal< sc_lv<25> > y_lo_s_V_reg_656;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<64> > zext_ln544_fu_353_p1;
    sc_signal< sc_lv<64> > zext_ln544_1_fu_358_p1;
    sc_signal< sc_lv<64> > zext_ln544_2_fu_448_p1;
    sc_signal< sc_lv<16> > x_l_V_fu_157_p0;
    sc_signal< sc_lv<16> > p_Result_15_fu_161_p1;
    sc_signal< sc_lv<16> > trunc_ln612_fu_171_p0;
    sc_signal< sc_lv<8> > trunc_ln612_fu_171_p1;
    sc_signal< sc_lv<16> > tmp_fu_183_p1;
    sc_signal< sc_lv<23> > x_l_V_fu_157_p1;
    sc_signal< sc_lv<1> > p_Result_s_fu_191_p3;
    sc_signal< sc_lv<1> > p_Result_1_fu_205_p3;
    sc_signal< sc_lv<1> > p_Result_2_fu_219_p3;
    sc_signal< sc_lv<1> > p_Result_3_fu_233_p3;
    sc_signal< sc_lv<1> > p_Result_4_fu_247_p3;
    sc_signal< sc_lv<1> > p_Result_5_fu_261_p3;
    sc_signal< sc_lv<1> > p_Result_6_fu_275_p3;
    sc_signal< sc_lv<1> > p_Result_7_fu_289_p3;
    sc_signal< sc_lv<4> > p_Result_15_fu_161_p4;
    sc_signal< sc_lv<11> > p_Result_16_fu_175_p3;
    sc_signal< sc_lv<1> > icmp_ln1498_fu_303_p2;
    sc_signal< sc_lv<1> > icmp_ln1494_fu_309_p2;
    sc_signal< sc_lv<16> > p_Result_s_19_fu_321_p1;
    sc_signal< sc_lv<16> > tmp_V_fu_331_p1;
    sc_signal< sc_lv<16> > trunc_ln612_1_fu_341_p0;
    sc_signal< sc_lv<5> > tmp_V_1_fu_345_p3;
    sc_signal< sc_lv<5> > tmp_V_fu_331_p4;
    sc_signal< sc_lv<1> > xor_ln191_fu_199_p2;
    sc_signal< sc_lv<1> > xor_ln191_1_fu_213_p2;
    sc_signal< sc_lv<1> > xor_ln191_2_fu_227_p2;
    sc_signal< sc_lv<1> > xor_ln191_3_fu_241_p2;
    sc_signal< sc_lv<1> > or_ln194_1_fu_369_p2;
    sc_signal< sc_lv<1> > or_ln194_fu_363_p2;
    sc_signal< sc_lv<1> > xor_ln191_4_fu_255_p2;
    sc_signal< sc_lv<1> > xor_ln191_5_fu_269_p2;
    sc_signal< sc_lv<1> > xor_ln191_7_fu_297_p2;
    sc_signal< sc_lv<1> > and_ln194_fu_315_p2;
    sc_signal< sc_lv<1> > or_ln194_4_fu_387_p2;
    sc_signal< sc_lv<1> > xor_ln191_6_fu_283_p2;
    sc_signal< sc_lv<1> > or_ln194_5_fu_393_p2;
    sc_signal< sc_lv<1> > or_ln194_3_fu_381_p2;
    sc_signal< sc_lv<1> > or_ln194_6_fu_399_p2;
    sc_signal< sc_lv<1> > or_ln194_2_fu_375_p2;
    sc_signal< sc_lv<18> > p_Result_18_fu_417_p4;
    sc_signal< sc_lv<18> > r_V_5_fu_432_p0;
    sc_signal< sc_lv<25> > r_V_5_fu_432_p1;
    sc_signal< sc_lv<43> > r_V_5_fu_432_p2;
    sc_signal< sc_lv<5> > p_Result_17_fu_411_p3;
    sc_signal< sc_lv<19> > rhs_V_fu_456_p5;
    sc_signal< sc_lv<20> > lhs_V_fu_453_p1;
    sc_signal< sc_lv<20> > zext_ln728_fu_466_p1;
    sc_signal< sc_lv<20> > ret_V_fu_470_p2;
    sc_signal< sc_lv<25> > zext_ln703_fu_476_p1;
    sc_signal< sc_lv<25> > r_V_6_fu_491_p0;
    sc_signal< sc_lv<25> > r_V_6_fu_491_p1;
    sc_signal< sc_lv<50> > r_V_6_fu_491_p2;
    sc_signal< sc_lv<1> > xor_ln195_fu_507_p2;
    sc_signal< sc_lv<25> > y_l_V_fu_520_p2;
    sc_signal< sc_lv<22> > select_ln195_fu_512_p3;
    sc_signal< sc_lv<22> > y_V_fu_524_p4;
    sc_signal< sc_lv<22> > p_Val2_10_fu_534_p3;
    sc_signal< sc_lv<2> > tmp_4_fu_551_p4;
    sc_signal< sc_lv<2> > tmp_3_fu_541_p4;
    sc_signal< sc_lv<2> > or_ln255_fu_561_p2;
    sc_signal< sc_lv<1> > icmp_ln255_fu_567_p2;
    sc_signal< sc_lv<16> > tmp_2_fu_573_p4;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to4;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<43> > r_V_5_fu_432_p00;
    sc_signal< sc_lv<43> > r_V_5_fu_432_p10;
    sc_signal< sc_lv<50> > r_V_6_fu_491_p00;
    sc_signal< sc_lv<50> > r_V_6_fu_491_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<11> ap_const_lv11_500;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<22> ap_const_lv22_3FFFFF;
    static const sc_lv<22> ap_const_lv22_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<16> ap_const_lv16_7FFF;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_and_ln194_fu_315_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to4();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_return();
    void thread_exp_x_msb_1_table_V_address0();
    void thread_exp_x_msb_1_table_V_ce0();
    void thread_exp_x_msb_2_lsb_m_1_s_fu_480_p2();
    void thread_exp_x_msb_2_m_1_tabl_address0();
    void thread_exp_x_msb_2_m_1_tabl_ce0();
    void thread_f_x_lsb_table_V_address0();
    void thread_f_x_lsb_table_V_ce0();
    void thread_icmp_ln1494_fu_309_p2();
    void thread_icmp_ln1498_fu_303_p2();
    void thread_icmp_ln255_fu_567_p2();
    void thread_lhs_V_fu_453_p1();
    void thread_or_ln194_1_fu_369_p2();
    void thread_or_ln194_2_fu_375_p2();
    void thread_or_ln194_3_fu_381_p2();
    void thread_or_ln194_4_fu_387_p2();
    void thread_or_ln194_5_fu_393_p2();
    void thread_or_ln194_6_fu_399_p2();
    void thread_or_ln194_7_fu_405_p2();
    void thread_or_ln194_fu_363_p2();
    void thread_or_ln255_fu_561_p2();
    void thread_p_Result_15_fu_161_p1();
    void thread_p_Result_15_fu_161_p4();
    void thread_p_Result_16_fu_175_p3();
    void thread_p_Result_17_fu_411_p3();
    void thread_p_Result_18_fu_417_p4();
    void thread_p_Result_1_fu_205_p3();
    void thread_p_Result_2_fu_219_p3();
    void thread_p_Result_3_fu_233_p3();
    void thread_p_Result_4_fu_247_p3();
    void thread_p_Result_5_fu_261_p3();
    void thread_p_Result_6_fu_275_p3();
    void thread_p_Result_7_fu_289_p3();
    void thread_p_Result_s_19_fu_321_p1();
    void thread_p_Result_s_fu_191_p3();
    void thread_p_Val2_10_fu_534_p3();
    void thread_r_V_5_fu_432_p0();
    void thread_r_V_5_fu_432_p00();
    void thread_r_V_5_fu_432_p1();
    void thread_r_V_5_fu_432_p10();
    void thread_r_V_5_fu_432_p2();
    void thread_r_V_6_fu_491_p0();
    void thread_r_V_6_fu_491_p00();
    void thread_r_V_6_fu_491_p1();
    void thread_r_V_6_fu_491_p10();
    void thread_r_V_6_fu_491_p2();
    void thread_ret_V_fu_470_p2();
    void thread_rhs_V_fu_456_p5();
    void thread_select_ln195_fu_512_p3();
    void thread_tmp_2_fu_573_p4();
    void thread_tmp_3_fu_541_p4();
    void thread_tmp_4_fu_551_p4();
    void thread_tmp_V_1_fu_345_p3();
    void thread_tmp_V_fu_331_p1();
    void thread_tmp_V_fu_331_p4();
    void thread_tmp_fu_183_p1();
    void thread_tmp_fu_183_p3();
    void thread_trunc_ln612_1_fu_341_p0();
    void thread_trunc_ln612_1_fu_341_p1();
    void thread_trunc_ln612_fu_171_p0();
    void thread_trunc_ln612_fu_171_p1();
    void thread_x_l_V_fu_157_p0();
    void thread_x_l_V_fu_157_p1();
    void thread_xor_ln191_1_fu_213_p2();
    void thread_xor_ln191_2_fu_227_p2();
    void thread_xor_ln191_3_fu_241_p2();
    void thread_xor_ln191_4_fu_255_p2();
    void thread_xor_ln191_5_fu_269_p2();
    void thread_xor_ln191_6_fu_283_p2();
    void thread_xor_ln191_7_fu_297_p2();
    void thread_xor_ln191_fu_199_p2();
    void thread_xor_ln195_fu_507_p2();
    void thread_y_V_fu_524_p4();
    void thread_y_l_V_fu_520_p2();
    void thread_zext_ln544_1_fu_358_p1();
    void thread_zext_ln544_2_fu_448_p1();
    void thread_zext_ln544_fu_353_p1();
    void thread_zext_ln703_fu_476_p1();
    void thread_zext_ln728_fu_466_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
