-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity post_process is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    sub0_val_output_V : IN STD_LOGIC_VECTOR (15 downto 0);
    sub1_val_output_V : IN STD_LOGIC_VECTOR (15 downto 0);
    sub2_val_output_V : IN STD_LOGIC_VECTOR (15 downto 0);
    sub3_val_output_V : IN STD_LOGIC_VECTOR (15 downto 0);
    input_ch_idx : IN STD_LOGIC_VECTOR (3 downto 0);
    val_output_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of post_process is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

    signal sub3_val_output_V_re_reg_428 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sub3_val_output_V_re_reg_428_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sub2_val_output_V_re_reg_434 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub1_val_output_V_re_reg_440 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_4_fu_166_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_4_reg_446 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_7_reg_452 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_9_fu_281_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_9_reg_459 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_8_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln211_fu_70_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_76_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_V_fu_88_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_V_fu_88_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_fu_84_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_fu_92_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_3_fu_106_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_3_fu_106_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_4_fu_112_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_98_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_16_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_150_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_fu_158_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_V_1_fu_177_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_1_fu_174_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_1_fu_180_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_6_fu_194_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_6_fu_198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_fu_186_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_2_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_9_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_17_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_11_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_9_fu_236_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_9_fu_244_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_7_fu_252_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_V_2_fu_264_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_2_fu_260_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_2_fu_267_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal xor_ln786_3_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_10_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_18_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_12_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_10_fu_318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_10_fu_325_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_10_fu_332_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_V_3_fu_344_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal lhs_V_3_fu_340_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_3_fu_347_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_12_fu_361_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_10_fu_366_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_353_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_4_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_11_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_19_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_13_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_11_fu_404_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_11_fu_412_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln340_21_fu_420_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal sub0_val_output_V_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sub1_val_output_V_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sub2_val_output_V_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal sub3_val_output_V_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal input_ch_idx_int_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal val_output_V_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (15 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln340_21_fu_420_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                input_ch_idx_int_reg <= input_ch_idx;
                sub0_val_output_V_int_reg <= sub0_val_output_V;
                sub1_val_output_V_int_reg <= sub1_val_output_V;
                sub2_val_output_V_int_reg <= sub2_val_output_V;
                sub3_val_output_V_int_reg <= sub3_val_output_V;
                val_output_V_int_reg <= val_output_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Result_7_reg_452 <= ret_V_2_fu_267_p2(16 downto 16);
                p_Result_8_reg_465 <= p_Val2_9_fu_281_p2(15 downto 15);
                p_Val2_4_reg_446 <= p_Val2_4_fu_166_p3;
                p_Val2_9_reg_459 <= p_Val2_9_fu_281_p2;
                sub1_val_output_V_re_reg_440 <= sub1_val_output_V_int_reg;
                sub2_val_output_V_re_reg_434 <= sub2_val_output_V_int_reg;
                sub3_val_output_V_re_reg_428 <= sub3_val_output_V_int_reg;
                sub3_val_output_V_re_reg_428_pp0_iter1_reg <= sub3_val_output_V_re_reg_428;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln340_21_fu_420_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln340_21_fu_420_p3;
        end if; 
    end process;

    icmp_ln211_fu_70_p2 <= "1" when (input_ch_idx_int_reg = ap_const_lv4_0) else "0";
        lhs_V_1_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_reg_446),17));

        lhs_V_2_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_fu_252_p3),17));

        lhs_V_3_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_10_fu_332_p3),17));

        lhs_V_fu_84_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_76_p3),17));

    or_ln340_11_fu_230_p2 <= (xor_ln340_9_fu_224_p2 or p_Result_6_fu_198_p3);
    or_ln340_12_fu_313_p2 <= (xor_ln340_10_fu_308_p2 or p_Result_8_reg_465);
    or_ln340_13_fu_398_p2 <= (xor_ln340_11_fu_392_p2 or p_Result_10_fu_366_p3);
    or_ln340_fu_144_p2 <= (xor_ln340_fu_138_p2 or p_Result_4_fu_112_p3);
    p_Result_10_fu_366_p3 <= p_Val2_12_fu_361_p2(15 downto 15);
    p_Result_4_fu_112_p3 <= p_Val2_3_fu_106_p2(15 downto 15);
    p_Result_5_fu_186_p3 <= ret_V_1_fu_180_p2(16 downto 16);
    p_Result_6_fu_198_p3 <= p_Val2_6_fu_194_p2(15 downto 15);
    p_Result_9_fu_353_p3 <= ret_V_3_fu_347_p2(16 downto 16);
    p_Result_s_fu_98_p3 <= ret_V_fu_92_p2(16 downto 16);
    p_Val2_10_fu_332_p3 <= 
        select_ln340_10_fu_318_p3 when (or_ln340_12_fu_313_p2(0) = '1') else 
        select_ln388_10_fu_325_p3;
    p_Val2_12_fu_361_p2 <= std_logic_vector(signed(p_Val2_10_fu_332_p3) + signed(sub3_val_output_V_re_reg_428_pp0_iter1_reg));
    p_Val2_3_fu_106_p1 <= sub0_val_output_V_int_reg;
    p_Val2_3_fu_106_p2 <= std_logic_vector(signed(p_Val2_s_fu_76_p3) + signed(p_Val2_3_fu_106_p1));
    p_Val2_4_fu_166_p3 <= 
        select_ln340_fu_150_p3 when (or_ln340_fu_144_p2(0) = '1') else 
        select_ln388_fu_158_p3;
    p_Val2_6_fu_194_p2 <= std_logic_vector(signed(p_Val2_4_reg_446) + signed(sub1_val_output_V_re_reg_440));
    p_Val2_7_fu_252_p3 <= 
        select_ln340_9_fu_236_p3 when (or_ln340_11_fu_230_p2(0) = '1') else 
        select_ln388_9_fu_244_p3;
    p_Val2_9_fu_281_p2 <= std_logic_vector(signed(p_Val2_7_fu_252_p3) + signed(sub2_val_output_V_re_reg_434));
    p_Val2_s_fu_76_p3 <= 
        ap_const_lv16_0 when (icmp_ln211_fu_70_p2(0) = '1') else 
        val_output_V_int_reg;
    ret_V_1_fu_180_p2 <= std_logic_vector(signed(rhs_V_1_fu_177_p1) + signed(lhs_V_1_fu_174_p1));
    ret_V_2_fu_267_p2 <= std_logic_vector(signed(rhs_V_2_fu_264_p1) + signed(lhs_V_2_fu_260_p1));
    ret_V_3_fu_347_p2 <= std_logic_vector(signed(rhs_V_3_fu_344_p1) + signed(lhs_V_3_fu_340_p1));
    ret_V_fu_92_p2 <= std_logic_vector(signed(rhs_V_fu_88_p1) + signed(lhs_V_fu_84_p1));
        rhs_V_1_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub1_val_output_V_re_reg_440),17));

        rhs_V_2_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub2_val_output_V_re_reg_434),17));

        rhs_V_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub3_val_output_V_re_reg_428_pp0_iter1_reg),17));

    rhs_V_fu_88_p0 <= sub0_val_output_V_int_reg;
        rhs_V_fu_88_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rhs_V_fu_88_p0),17));

    select_ln340_10_fu_318_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_18_fu_304_p2(0) = '1') else 
        p_Val2_9_reg_459;
    select_ln340_11_fu_404_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_19_fu_386_p2(0) = '1') else 
        p_Val2_12_fu_361_p2;
    select_ln340_21_fu_420_p3 <= 
        select_ln340_11_fu_404_p3 when (or_ln340_13_fu_398_p2(0) = '1') else 
        select_ln388_11_fu_412_p3;
    select_ln340_9_fu_236_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_17_fu_218_p2(0) = '1') else 
        p_Val2_6_fu_194_p2;
    select_ln340_fu_150_p3 <= 
        ap_const_lv16_7FFF when (xor_ln340_16_fu_132_p2(0) = '1') else 
        p_Val2_3_fu_106_p2;
    select_ln388_10_fu_325_p3 <= 
        ap_const_lv16_8000 when (underflow_2_fu_299_p2(0) = '1') else 
        p_Val2_9_reg_459;
    select_ln388_11_fu_412_p3 <= 
        ap_const_lv16_8000 when (underflow_3_fu_380_p2(0) = '1') else 
        p_Val2_12_fu_361_p2;
    select_ln388_9_fu_244_p3 <= 
        ap_const_lv16_8000 when (underflow_1_fu_212_p2(0) = '1') else 
        p_Val2_6_fu_194_p2;
    select_ln388_fu_158_p3 <= 
        ap_const_lv16_8000 when (underflow_fu_126_p2(0) = '1') else 
        p_Val2_3_fu_106_p2;
    underflow_1_fu_212_p2 <= (xor_ln786_2_fu_206_p2 and p_Result_5_fu_186_p3);
    underflow_2_fu_299_p2 <= (xor_ln786_3_fu_294_p2 and p_Result_7_reg_452);
    underflow_3_fu_380_p2 <= (xor_ln786_4_fu_374_p2 and p_Result_9_fu_353_p3);
    underflow_fu_126_p2 <= (xor_ln786_fu_120_p2 and p_Result_s_fu_98_p3);
    xor_ln340_10_fu_308_p2 <= (p_Result_7_reg_452 xor ap_const_lv1_1);
    xor_ln340_11_fu_392_p2 <= (p_Result_9_fu_353_p3 xor ap_const_lv1_1);
    xor_ln340_16_fu_132_p2 <= (p_Result_s_fu_98_p3 xor p_Result_4_fu_112_p3);
    xor_ln340_17_fu_218_p2 <= (p_Result_6_fu_198_p3 xor p_Result_5_fu_186_p3);
    xor_ln340_18_fu_304_p2 <= (p_Result_8_reg_465 xor p_Result_7_reg_452);
    xor_ln340_19_fu_386_p2 <= (p_Result_9_fu_353_p3 xor p_Result_10_fu_366_p3);
    xor_ln340_9_fu_224_p2 <= (p_Result_5_fu_186_p3 xor ap_const_lv1_1);
    xor_ln340_fu_138_p2 <= (p_Result_s_fu_98_p3 xor ap_const_lv1_1);
    xor_ln786_2_fu_206_p2 <= (p_Result_6_fu_198_p3 xor ap_const_lv1_1);
    xor_ln786_3_fu_294_p2 <= (p_Result_8_reg_465 xor ap_const_lv1_1);
    xor_ln786_4_fu_374_p2 <= (p_Result_10_fu_366_p3 xor ap_const_lv1_1);
    xor_ln786_fu_120_p2 <= (p_Result_4_fu_112_p3 xor ap_const_lv1_1);
end behav;
