# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xavier/MSc_Project/hls/yolo_conv_hls_2019/yolo_conv_fp_prj_2019_64/yolo_conv_fp_prj_2019_64.srcs/sources_1/bd/design_1/ip/design_1_yolo_conv_top_0_7/design_1_yolo_conv_top_0_7.xci
# IP: The module: 'design_1_yolo_conv_top_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xavier/MSc_Project/hls/yolo_conv_hls_2019/yolo_conv_fp_prj_2019_64/yolo_conv_fp_prj_2019_64.srcs/sources_1/bd/design_1/ip/design_1_yolo_conv_top_0_7/constraints/yolo_conv_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_yolo_conv_top_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/xavier/MSc_Project/hls/yolo_conv_hls_2019/yolo_conv_fp_prj_2019_64/yolo_conv_fp_prj_2019_64.srcs/sources_1/bd/design_1/ip/design_1_yolo_conv_top_0_7/design_1_yolo_conv_top_0_7.xci
# IP: The module: 'design_1_yolo_conv_top_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xavier/MSc_Project/hls/yolo_conv_hls_2019/yolo_conv_fp_prj_2019_64/yolo_conv_fp_prj_2019_64.srcs/sources_1/bd/design_1/ip/design_1_yolo_conv_top_0_7/constraints/yolo_conv_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_yolo_conv_top_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
